UNIT_TYPE_TRIAL = "trial"
UNIT_TYPE_NORMAL = "normal"

BLOCK_TYPE_CONTENT = "content"
BLOCK_TYPE_BREAK = "break"
BLOCK_TYPE_BUTTON = "button"
BLOCK_TYPE_INPUT = "input"
BLOCK_TYPE_OPTIONS = "options"
BLOCK_TYPE_GOTO = "goto"
BLOCK_TYPE_PAYMENT = "payment"
BLOCK_TYPE_LOGIN = "login"


UNIT_TYPE_VALUE_TRIAL = 401
UNIT_TYPE_VALUE_NORMAL = 402

UNIT_TYPE_VALUES = {
    UNIT_TYPE_TRIAL: UNIT_TYPE_VALUE_TRIAL,
    UNIT_TYPE_NORMAL: UNIT_TYPE_VALUE_NORMAL,
}

UNIT_TYPE_VALUES_REVERSE = {v: k for k, v in UNIT_TYPE_VALUES.items()}
