cookie:
  expiry_days: 7
  key: eKr_0pdK5bK3L3SFSLU0fLUI7gMFsGnDMNgE19YHKNU
  name: codesifu_user_reauth_cookie
credentials:
  usernames:
    '017':
      email: 15510550064@163.com
      failed_login_attempts: 3
      logged_in: false
      name: '017'
      password: $2b$12$3Cy7rccuIiFhxYT/mQ97Oexb585D6z64ubBEtTrj1o46vJOOvg4qC
    kenrick:
      email: Kenrick.Zhou@gmail.com
      failed_login_attempts: 3
      logged_in: false
      name: KenrickZ
      password: $2b$12$PXvcCwh8eZEGBxz.upGnCuzlsdZn1qT3gXZuj/w7XDYksJQFOSIOm
    sunner:
      email: sunner@gmail.com
      failed_login_attempts: 3
      logged_in: false
      name: 'Sun Zhigang'
      password: ai-shifu
    yfge:
      email: geyunfei@gmail.com
      failed_login_attempts: 3
      logged_in: false
      name: 'yfge'
      password: ai-shifu
pre-authorized:
  emails:
  - abc@gmail.com
