simulate_streaming_random_sleep:
  min: 0.001  # 0.005
  max: 0.02  # 0.2

llm:
#  default_vendor: wenxin
  default_model: ERNIE-4.0-8K-Preview-0518
  qianfan:
    models:
      - ERNIE-4.0-8K-0329
      - ERNIE-4.0-8K-Preview-0518
      - ERNIE-3.5-8K-0329
#      - ERNIE-Speed-8K
    default_temperature: 0.4  # (0, 1.0]，官方文档默认 0.8，但Langchain源码里默认 0.95
  zhipu:
    models:
      - GLM-4-0520
      - GLM-4
      - GLM-3-Turbo
    default_temperature: 0.4  # (0, 1.0), 官方默认 0.95
  openai:
    models:
#      - gpt-4
#      - gpt-4o
#      - gpt-3.5-turbo
      - gpt-4o-2024-05-13
      - gpt-4-0125-preview
      - gpt-4-turbo-2024-04-09
      - gpt-3.5-turbo-0125

    organization: org-fC5Q2f4MQIEaTOa3k8vTQu6G
    default_temperature: 0.4  # [0, 2.0]

lark:
  app_token: LLwmbSyMcakFVJsM5yacT5Gqnse
  default_table_id: tblk9OFSKLeUPunv  # 《剧本》：00-了解 AI 编程这回事

#  app_token: MOpQbqTG3ai5I3sqymUcMK1rnti  # 《剧本v2(0718)》
#  default_table_id: tblm5XfXmxv2VFhN  # 《剧本v2(0718)》：01- 如何向 AI 提项目需求？
#  table_id: tblMGLpPFYWU0gIK  # 试学课 test01
#  table_id: tbltsSzDfJQm6dne  # 在自己电脑上运行Python
  default_view_id: vewlGkI2Jp

fileupload:
  img_local_dir: /tmp/codesifu/img
  img_oss_aname: img.agiclass.cn
  img_oss_endpoint: https://oss-cn-beijing.aliyuncs.com
  img_oss_bucket: codesifu-img

db:
  sqlite:
    path: codesifu-demo.db

api:
  test_url: https://test-api-sifu.agiclass.cn/api
  prod_url: https://api-sifu.agiclass.cn/api
