"""add course banner url

Revision ID: 1819ffc918d3
Revises: bed6fe23f09b
Create Date: 2024-12-17 03:35:50.799930

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1819ffc918d3"
down_revision = "bed6fe23f09b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_banner_url",
                sa.String(length=255),
                nullable=False,
                comment="Course banner url",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.drop_column("course_banner_url")

    # ### end Alembic commands ###
