"""fix_update_profile_comments

Revision ID: 4d97ba5c8faf
Revises: 31f18de7e03e
Create Date: 2025-08-16 15:25:51.722471

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4d97ba5c8faf"
down_revision = "31f18de7e03e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_lesson", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=mysql.INTEGER(),
            comment="Status of the lesson: 0-delete ,1-publish,2-draft",
            existing_comment="Status of the lesson",
            existing_nullable=False,
        )

    with op.batch_alter_table("order_banner_info", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=mysql.BIGINT(),
            comment="Unique ID",
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("profile_item", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(),
            comment="profile type: 2900=input_unconf, 2901=input_text, 2902=input_number, 2903=input_select, 2904=input_sex, 2905=input_date",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_value_type",
            existing_type=mysql.INTEGER(),
            comment="profile value type: 3001=all, 3002=specific",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_show_type",
            existing_type=mysql.INTEGER(),
            comment="profile show type: 3001=all, 3002=user, 3003=course, 3004=hidden",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_prompt_type",
            existing_type=mysql.INTEGER(),
            comment="profile prompt type: 3101=profile, 3102=item",
            existing_nullable=False,
        )

    with op.batch_alter_table("profile_item_i18n", schema=None) as batch_op:
        batch_op.alter_column(
            "conf_type",
            existing_type=mysql.INTEGER(),
            comment="profile conf type: 3101=profile, 3102=item",
            existing_nullable=False,
        )

    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(),
            comment="profile type: 2900=input_unconf, 2901=input_text, 2902=input_number, 2903=input_select, 2904=input_sex, 2905=input_date",
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile type: 2900=input_unconf, 2901=input_text, 2902=input_number, 2903=input_select, 2904=input_sex, 2905=input_date",
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    with op.batch_alter_table("profile_item_i18n", schema=None) as batch_op:
        batch_op.alter_column(
            "conf_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile conf type: 3101=profile, 3102=item",
            existing_nullable=False,
        )

    with op.batch_alter_table("profile_item", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_prompt_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile prompt type: 3101=profile, 3102=item",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_show_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile show type: 3001=all, 3002=user, 3003=course, 3004=hidden",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_value_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile value type: 3001=all, 3002=specific",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(),
            comment=None,
            existing_comment="profile type: 2900=input_unconf, 2901=input_text, 2902=input_number, 2903=input_select, 2904=input_sex, 2905=input_date",
            existing_nullable=False,
        )

    with op.batch_alter_table("order_banner_info", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=mysql.BIGINT(),
            comment=None,
            existing_comment="Unique ID",
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_lesson", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=mysql.INTEGER(),
            comment="Status of the lesson",
            existing_comment="Status of the lesson: 0-delete ,1-publish,2-draft",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
