"""add course model cleanup audit ledger

Revision ID: 5ca8717e482f
Revises: fde432bceab4
Create Date: 2026-09-17 19:23:39.747131

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5ca8717e482f"
down_revision = "fde432bceab4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add only the cleanup audit ledger; course model columns already exist."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shifu_model_tier_migration_audit",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("batch_bid", sa.String(length=32), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("row_id", mysql.BIGINT(), nullable=False),
        sa.Column("field_name", sa.String(length=32), nullable=False),
        sa.Column("previous_model", sa.String(length=100), nullable=True),
        sa.Column("new_model", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "shifu_model_tier_migration_audit", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_model_tier_audit_selection",
            ["table_name", "row_id", "field_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_shifu_model_tier_migration_audit_batch_bid"),
            ["batch_bid"],
            unique=False,
        )


def downgrade() -> None:
    """Remove the cleanup audit ledger without changing course selections."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "shifu_model_tier_migration_audit", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_model_tier_audit_selection")
        batch_op.drop_index(batch_op.f("ix_shifu_model_tier_migration_audit_batch_bid"))

    op.drop_table("shifu_model_tier_migration_audit")
    # ### end Alembic commands ###
