"""change course_collapsed_banner_url name

Revision ID: 7f7365b481ab
Revises: ec9cbac857bc
Create Date: 2024-12-17 08:51:30.751199

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7f7365b481ab"
down_revision = "ec9cbac857bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_collapsed_banner_url",
                sa.String(length=255),
                nullable=False,
                comment="Course banner collapse url",
            )
        )
        batch_op.drop_column("course_banner_collapse_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_banner_collapse_url",
                mysql.VARCHAR(length=255),
                nullable=False,
                comment="Course banner collapse url",
            )
        )
        batch_op.drop_column("course_collapsed_banner_url")

    # ### end Alembic commands ###
