"""drop admin_info table

Revision ID: a1b2c3d4e5f6
Revises: f50666697df7
Create Date: 2025-08-10 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "f50666697df7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_info")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate admin_info table structure (from original creation migration)
    op.create_table(
        "admin_info",
        sa.Column(
            "id",
            sa.BIGINT(),
            autoincrement=True,
            nullable=False,
            comment="Unique ID",
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="User UUID"),
        sa.Column(
            "username", sa.String(length=255), nullable=False, comment="Login username"
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="User real name"
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Hashed password",
        ),
        sa.Column("email", sa.String(length=255), nullable=False, comment="Email"),
        sa.Column("mobile", sa.String(length=20), nullable=False, comment="Mobile"),
        sa.Column(
            "created",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
            comment="Creation time",
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            comment="Update time",
        ),
        sa.Column("user_state", sa.Integer(), nullable=True, comment="User_state"),
        sa.Column("user_sex", sa.Integer(), nullable=True, comment="user sex"),
        sa.Column("user_birth", sa.Date(), nullable=True, comment="user birth"),
        sa.Column(
            "user_avatar", sa.String(length=255), nullable=True, comment="user avatar"
        ),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
            comment="is admin",
        ),
        sa.Column(
            "is_creator",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
            comment="is creator",
        ),
        sa.Column(
            "user_language",
            sa.String(length=30),
            nullable=True,
            server_default=sa.text("'zh-CN'"),
            comment="user language",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
