"""remove course model cleanup audit

Revision ID: abbe9d73bdb1
Revises: 5ca8717e482f
Create Date: 2026-09-19 12:08:59.662241

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abbe9d73bdb1"
down_revision = "5ca8717e482f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Retire the cleanup ledger without changing course model selections."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "shifu_model_tier_migration_audit", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_model_tier_audit_selection")
        batch_op.drop_index("ix_shifu_model_tier_migration_audit_batch_bid")

    op.drop_table("shifu_model_tier_migration_audit")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore only the legacy ledger schema; deleted audit rows need a backup."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shifu_model_tier_migration_audit",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("batch_bid", sa.VARCHAR(length=32), nullable=False),
        sa.Column("table_name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("row_id", sa.BIGINT(), nullable=False),
        sa.Column("field_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("previous_model", sa.VARCHAR(length=100), nullable=True),
        sa.Column("new_model", sa.VARCHAR(length=100), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "shifu_model_tier_migration_audit", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_shifu_model_tier_migration_audit_batch_bid", ["batch_bid"], unique=False
        )
        batch_op.create_index(
            "ix_model_tier_audit_selection",
            ["table_name", "row_id", "field_name"],
            unique=False,
        )

    # ### end Alembic commands ###
