"""fix course_teacher_avator to course_teacher_avatar

Revision ID: ce6996daf20a
Revises: f50666697df7
Create Date: 2025-04-12 16:07:20.761956

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce6996daf20a"
down_revision = "f50666697df7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_teacher_avatar",
                sa.String(length=255),
                nullable=False,
                comment="Course teacher avatar",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.drop_column("course_teacher_avatar")

    # ### end Alembic commands ###
