"""add course banner collapse url

Revision ID: ec9cbac857bc
Revises: 1819ffc918d3
Create Date: 2024-12-17 04:26:39.547337

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec9cbac857bc"
down_revision = "1819ffc918d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_banner_collapse_url",
                sa.String(length=255),
                nullable=False,
                comment="Course banner collapse url",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.drop_column("course_banner_collapse_url")

    # ### end Alembic commands ###
