#!/usr/bin/env bash
# Idempotent Cloud Agent install for AI-Shifu.
# Provisions native MySQL + Redis, the Python backend venv, and the cook-web
# frontend dependencies, then applies DB migrations and imports the demo course.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${AI_SHIFU_VENV:-$HOME/.venvs/ai-shifu}"

echo "[install] repo root: $REPO_ROOT"

# 1) System packages: database, cache, media (pydub/ffmpeg) and build toolchain.
if ! command -v mysqld >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
  echo "[install] installing system packages"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -y
  sudo apt-get install -y --no-install-recommends \
    mysql-server redis-server ffmpeg \
    python3.12-venv python3-dev build-essential pkg-config curl
fi

# 2) Start MySQL + Redis so migrations can run (safe to call repeatedly).
bash "$REPO_ROOT/.cursor/start.sh"

# 3) Application database and TCP user (idempotent). A dedicated user avoids the
#    root@localhost socket-auth account that 127.0.0.1 resolves to.
sudo mysql <<'SQL'
CREATE DATABASE IF NOT EXISTS `ai-shifu` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'aishifu'@'%' IDENTIFIED WITH caching_sha2_password BY 'ai-shifu';
ALTER USER 'aishifu'@'%' IDENTIFIED WITH caching_sha2_password BY 'ai-shifu';
GRANT ALL PRIVILEGES ON *.* TO 'aishifu'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SQL

# 4) Python virtualenv + backend dependencies.
if [ ! -x "$VENV_DIR/bin/python" ]; then
  python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
python -m pip install --upgrade "pip<25" setuptools wheel
pip install -r "$REPO_ROOT/src/api/requirements.txt"

# 5) Backend .env for local native services. Only created when missing so that
#    real secrets (e.g. a working LLM key) added later are preserved.
API_ENV="$REPO_ROOT/src/api/.env"
if [ ! -f "$API_ENV" ]; then
  echo "[install] writing $API_ENV"
  cat > "$API_ENV" <<ENV
# Local Cloud Agent development configuration (generated by .cursor/install.sh).
# Not for production. A real LLM key can be provided via an environment secret
# (OPENAI_API_KEY), which takes precedence over the placeholder below.
ENV="development"
MODE="api"
FLASK_APP="app.py"
SWAGGER_ENABLED="True"
SQLALCHEMY_DATABASE_URI="mysql://aishifu:ai-shifu@127.0.0.1:3306/ai-shifu?charset=utf8mb4"
REDIS_HOST="127.0.0.1"
REDIS_PORT="6379"
SECRET_KEY="ai-shifu-local-dev-secret"
UNIVERSAL_VERIFICATION_CODE="1024"
CAPTCHA_CODE_OVERRIDE="0000"
LOGIN_METHODS_ENABLED="phone"
DEFAULT_LOGIN_METHOD="phone"
ADMIN_LOGIN_GRANT_CREATOR_WITH_DEMO="True"
OPENAI_API_KEY="PLACEHOLDER_SET_A_REAL_LLM_KEY_FOR_GENERATION"
SHARED_I18N_ROOT="$REPO_ROOT/src/i18n"
CELERY_BROKER_URL="redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND="redis://127.0.0.1:6379/1"
ENV
fi

# 6) Database schema + demo course. The demo import tolerates a missing LLM key;
#    only its optional AI "summary" step is skipped without a real model.
cd "$REPO_ROOT/src/api"
export FLASK_APP=app.py
python scripts/repair_dev_migration_state.py || true
flask db upgrade
flask console update_demo_shifu || true

# 7) Frontend dependencies (exact, from lockfile).
cd "$REPO_ROOT/src/cook-web"
npm ci

echo "[install] done"
