#!/usr/bin/env bash
# Per-boot startup for the AI-Shifu Cloud Agent environment.
# Starts Redis and MySQL, ensures the database and a TCP root user exist,
# writes a local dev .env if missing, and applies DB migrations plus the
# bundled demo courses. This script must return; the long-running API and web
# servers run as `terminals` (see .cursor/environment.json).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[start] Starting Redis..."
sudo service redis-server start || true

echo "[start] Starting MySQL..."
sudo service mysql start || true
echo "[start] Waiting for MySQL to accept connections..."
for _ in $(seq 1 60); do
  if sudo mysqladmin ping >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "[start] Ensuring database and TCP root user (idempotent)..."
sudo mysql <<'SQL' || true
CREATE DATABASE IF NOT EXISTS `ai-shifu` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY 'ai-shifu';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED WITH caching_sha2_password BY 'ai-shifu';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SQL

ENV_FILE="$REPO_ROOT/src/api/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "[start] Writing local dev backend .env..."
  cat > "$ENV_FILE" <<'ENVEOF'
# Local development environment for AI-Shifu backend (Cloud Agent).
# Auto-generated by .cursor/start.sh. Not for production.
ENV="development"
FLASK_APP="app.py"
MODE="api"
PATH_PREFIX="/api"
SWAGGER_ENABLED="True"
TZ="UTC"

SECRET_KEY="ai-shifu-local-dev-secret-key-change-me-please"
UNIVERSAL_VERIFICATION_CODE="1024"
CAPTCHA_CODE_OVERRIDE="0000"

SQLALCHEMY_DATABASE_URI="mysql://root:ai-shifu@127.0.0.1:3306/ai-shifu?charset=utf8mb4"

REDIS_HOST="127.0.0.1"
REDIS_PORT="6379"
REDIS_DB="0"

CELERY_BROKER_URL="redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND="redis://127.0.0.1:6379/1"
CELERY_TASK_ALWAYS_EAGER="False"

# Placeholder LLM key so the backend passes its "at least one LLM key" startup
# check. Add a real provider key (e.g. a Cursor Secret named OPENAI_API_KEY)
# to enable live AI course generation; real env vars take precedence over this.
OPENAI_API_KEY="sk-placeholder-local-dev-only"

LOGIN_METHODS_ENABLED="phone"
DEFAULT_LOGIN_METHOD="phone"

CREATOR_INTEGRATION_ENCRYPTION_KEY="9KxIo7loUIAmGkQmxUHQWwLpyJBKdIIFxg9FgDtw9NI="
ENVEOF
else
  echo "[start] Existing src/api/.env found; leaving it untouched."
fi

echo "[start] Applying database migrations and demo courses..."
pushd src/api >/dev/null
# shellcheck disable=SC1091
. .venv/bin/activate
export FLASK_APP=app.py
python scripts/repair_dev_migration_state.py || true
flask db upgrade
flask console update_demo_shifu || true
deactivate
popd >/dev/null

echo "[start] Ready. API and web servers launch as terminals."
