version: '3.5'

services:
  ai-shifu-api:
    container_name: ai-shifu-api
    image: ai-shifu-api:latest
    command:  gunicorn -w 4 -b 0.0.0.0:5800 "flaskr:create_app()"  --timeout 300 --log-level debug --access-logfile /var/log/app.log  --capture-output
    environment:
      - FLASK_APP=flaskr
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5800
  ai-shifu-web:
    container_name:  ai-shifu-web
    image: ai-shifu-web:latest
    command:  ["serve", "-s", "build", "-l", "5000"]
    depends_on:
      - ai-shifu-api
  ai-shifu-admin-api:
    container_name: ai-shifu-admin-api
    image: ai-shifu-admin-api:latest
    command:  gunicorn -w 4 -b 0.0.0.0:5800 "flaskr:create_app()"  --timeout 300 --log-level debug --access-logfile /var/log/app.log  --capture-output
    environment:
      - FLASK_APP=flaskr
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5800
  ai-shifu-admin-web: 
    container_name:  ai-shifu-admin-web
    image: ai-shifu-admin-web:latest
    command:  ["serve", "-s", "build", "-l", "5000"]
    depends_on:
      - ai-shifu-api
    # ports: 
    #  - "5000:5000"
  ai-shifu-nginx:
    container_name: ai-shifu-nginx
    image: nginx:latest
    ports: 
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web
      - ai-shifu-api
      - ai-shifu-admin-web
      - ai-shifu-admin-api
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

