version: '3.5'

services:
  ai-shifu-api:
    container_name: ai-shifu-api
    image: ai-shifu-api:latest
    entrypoint: ["sh", "-c", "flask db upgrade && exec gunicorn -w 4 -b 0.0.0.0:5800 'app:app' --timeout 300 --log-level debug --access-logfile /var/log/app.log --capture-output"]
    env_file:
      - ./.env
  ai-shifu-web:
    container_name:  ai-shifu-web
    image: ai-shifu-web:latest
    command:  ["serve", "-s", "build", "-l", "5000"]
    depends_on:
      - ai-shifu-api
  ai-shifu-admin-api:
    container_name: ai-shifu-admin-api
    image: ai-shifu-api:latest
    command:  gunicorn -w 4 -b 0.0.0.0:5800 "app:app" --timeout 300 --log-level debug --access-logfile /var/log/app.log  --capture-output
    env_file:
      - ./.env
    environment:
      - MODE=admin
  ai-shifu-admin-web:
    container_name:  ai-shifu-admin-web
    image: ai-shifu-admin-web:latest
    command:  ["serve", "-s", "build", "-l", "5000"]
    depends_on:
      - ai-shifu-api
  ai-shifu-nginx:
    container_name: ai-shifu-nginx
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web
      - ai-shifu-api
      - ai-shifu-admin-web
      - ai-shifu-admin-api
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  ai-shifu-mysql:
    container_name: ai-shifu-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  ai-shifu-redis:
    container_name: ai-shifu-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

# en
