version: '3.5'

services:
  ai-shifu-api-dev:
    container_name: ai-shifu-api-dev
    image: ai-shifu-api-dev:latest
    command: flask run --debug  --host=0.0.0.0 --port=5800
    env_file:
      - ./.env
    volumes:
      - ../src/api/:/app/
  ai-shifu-web-dev:
    container_name:  ai-shifu-web-dev
    image: ai-shifu-web-dev:latest
    command:  pnpm run start:dev-local
    depends_on:
      - ai-shifu-api-dev
    volumes:
      - ../src/web:/usr/src/app
  ai-shifu-admin-api-dev:
    container_name: ai-shifu-admin-api-dev
    image: ai-shifu-api-dev:latest
    command:  flask run --debug  --host=0.0.0.0 --port=5800
    env_file:
      - ./.env
    environment:
      - MODE=admin
    volumes:
      - ../src/api/:/app/
  ai-shifu-admin-web-dev:
    container_name:  ai-shifu-admin-web-dev
    image: ai-shifu-admin-web-dev:latest
    command:  pnpm run start:dev
    depends_on:
      - ai-shifu-api-dev
    volumes:
      - ../src/admin-web:/usr/src/app
  ai-shifu-nginx-dev-dev:
    container_name: ai-shifu-nginx-dev
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ai-shifu-web-dev
      - ai-shifu-api-dev
      - ai-shifu-admin-web-dev
      - ai-shifu-admin-api-dev
    restart: always
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
