#!/usr/bin/env python3
"""Generate repository knowledge indexes and inventories."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from datetime import UTC, date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = ROOT / "docs"
GENERATED_COMMENT = (
    "<!-- Generated by scripts/build_repo_knowledge_index.py. Do not edit manually. -->"
)
FRONTMATTER_FIELDS = (
    "title",
    "status",
    "owner_surface",
    "last_reviewed",
    "canonical",
)
BOUNDARY_BASELINE_PATH = DOCS_ROOT / "generated" / "architecture-boundary-baseline.json"
HARNESS_HEALTH_PATH = DOCS_ROOT / "generated" / "harness-health.md"
GARDENING_SUMMARY_PATH = DOCS_ROOT / "generated" / "harness-gardening-summary.md"
REQUIRED_HARNESS_WORKFLOWS = (
    ROOT / ".github" / "workflows" / "repo-harness.yml",
    ROOT / ".github" / "workflows" / "runtime-harness.yml",
    ROOT / ".github" / "workflows" / "harness-gardening.yml",
)
REQUIRED_RUNTIME_ASSETS = (
    ROOT / "scripts" / "check_architecture_boundaries.py",
    ROOT / "src" / "api" / "scripts" / "harness_diagnostics.py",
    ROOT / "src" / "web" / "e2e" / "smoke.spec.ts",
    ROOT / "docker" / "docker-compose.dev.yml",
    ROOT / "docker" / "observability" / "loki-config.yml",
    ROOT / "docker" / "observability" / "tempo-config.yml",
    ROOT / "docker" / "observability" / "prometheus.yml",
    ROOT / "docker" / "observability" / "promtail-config.yml",
    ROOT / "docker" / "observability" / "otel-collector-config.yml",
)


@dataclass(frozen=True)
class DocRecord:
    """Record doc details."""

    path: Path
    title: str
    category: str
    status: str
    owner_surface: str
    last_reviewed: str
    canonical: str


FRONTMATTER_PATTERN = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
HEADING_PATTERN = re.compile(r"^#{1,6}\s+(.*)$", re.MULTILINE)


def parse_frontmatter(path: Path) -> dict[str, str]:
    """Return trimmed leading-frontmatter metadata, skipping missing or malformed entries."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_PATTERN.match(text)
    if not match:
        return {}
    metadata: dict[str, str] = {}
    current_key = ""
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if raw_line[0].isspace() and current_key:
            metadata[current_key] += " " + line
        elif ":" in line:
            key, value = line.split(":", 1)
            current_key = key.strip()
            metadata[current_key] = (
                "" if value.strip() in {"|", ">", "|-", ">-"} else value.strip()
            )
    return {key: value.strip().strip("\"'") for key, value in metadata.items()}


def parse_review_date(value: str) -> date:
    """Parse the shared YYYY-MM-DD review-date contract used by both checkers."""
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        message = "Review dates must use YYYY-MM-DD"
        raise ValueError(message)
    return date.fromisoformat(value)


def extract_title(path: Path) -> str:
    """Return a Markdown file's first heading or a title derived from its filename."""
    text = path.read_text(encoding="utf-8")
    match = HEADING_PATTERN.search(text)
    if match:
        return match.group(1).strip()
    return path.stem.replace("-", " ").title()


def tracked_markdown(root: Path | None = None) -> list[Path]:
    """List tracked Markdown/MDX sources, including staged additions and aliases."""
    root = ROOT if root is None else root
    output = subprocess.check_output(
        ["git", "ls-files", "-z", "--cached"], cwd=root, text=True
    )
    return sorted(
        {
            root / name
            for name in output.split("\0")
            if Path(name).suffix.lower() in {".md", ".mdx"}
            and ((root / name).is_file() or (root / name).is_symlink())
        }
    )


def focused_skills(paths: list[Path]) -> list[Path]:
    """Select dedicated skills while leaving routing SKILL files as navigation."""
    return [
        path
        for path in paths
        if path.name == "SKILL.md" and path.parent.parent.name == "skills"
    ]


def build_tracked_records() -> list[DocRecord]:
    """Classify every tracked document without inventing review dates."""
    records: list[DocRecord] = []
    canonical_roots = {
        "ARCHITECTURE.md",
        "PLANS.md",
        "docs/engineering-baseline.md",
        "docs/QUALITY_SCORE.md",
        "docs/RELIABILITY.md",
        "docs/SECURITY.md",
    }
    for path in tracked_markdown():
        rel = rel_doc(path)
        metadata = {} if path.is_symlink() else parse_frontmatter(path)
        title = (
            path.name
            if path.is_symlink()
            else metadata.get("title") or extract_title(path)
        )
        category, status = "reference", "reference"
        canonical = "true" if rel in canonical_roots else "false"
        if path.is_symlink() or rel == ".github/copilot-instructions.md":
            category, status = "alias", "alias"
        elif path.name == "AGENTS.md":
            category, status, canonical = "instruction", "current", "true"
        elif path.name == "SKILL.md":
            category = (
                "skill" if path.parent.parent.name == "skills" else "skill-router"
            )
            status = "current"
            canonical = "true" if category == "skill" else "false"
        elif rel.startswith("docs/history/"):
            category, status = "history", "historical"
        elif rel.startswith("docs/exec-plans/active/"):
            category, status, canonical = "exec-plan-active", "active", "true"
        elif rel.startswith("docs/exec-plans/completed/"):
            category, status = "exec-plan-completed", "completed"
        elif GENERATED_COMMENT in path.read_text(encoding="utf-8"):
            category, status = "generated-doc", "generated"
        elif rel.startswith("docs/design-docs/"):
            category, canonical = "design-doc", "true"
        elif rel.startswith("docs/product-specs/"):
            category, canonical = "product-spec", "true"
        elif rel.startswith("docs/references/"):
            canonical = "true"
        elif rel == "docs/exec-plans/tech-debt-tracker.md":
            category, status, canonical = "exec-plan-support", "active", "true"
        records.append(
            DocRecord(
                path=path,
                title=title,
                category=category,
                status=metadata.get("status") or status,
                owner_surface=metadata.get("owner_surface")
                or (
                    "frontend"
                    if rel.startswith("src/web/")
                    else "backend"
                    if rel.startswith("src/api/")
                    else "repo"
                ),
                last_reviewed=metadata.get("last_reviewed", ""),
                canonical=metadata.get("canonical") or canonical,
            )
        )
    return records


def render_skill_catalog(surface: str, skills: list[Path]) -> str:
    """Generate one discoverable catalog from focused skill metadata."""
    label = "Backend" if surface == "api" else "Frontend"
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {label} Skills",
        "",
        "Derived from the focused SKILL.md name and description metadata.",
        "",
    ]
    for path in skills:
        metadata = parse_frontmatter(path)
        name = metadata.get("name", path.parent.name)
        description = metadata.get("description", "")
        lines.append(f"- [{name}]({path.parent.name}/SKILL.md): {description}")
    return "\n".join(lines) + "\n"


def snapshot_provenance() -> list[str]:
    """Identify a local/CI working-tree snapshot without claiming test success."""
    try:
        revision = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        revision = "unavailable (no commit)"
    generated_at = (
        datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")
    )
    return [
        f"- Generated at (UTC): `{generated_at}`",
        f"- Checkout HEAD: `{revision}`",
        "- Scope: current working tree; local edits may differ from HEAD.",
    ]


def build_frontmatter_records(category_dir: Path, category: str) -> list[DocRecord]:
    """Build category-tagged records for non-index Markdown files in one metadata directory."""
    records: list[DocRecord] = []
    for path in sorted(category_dir.glob("*.md")):
        if path.name == "index.md":
            continue
        metadata = parse_frontmatter(path)
        title = metadata.get("title") or extract_title(path)
        records.append(
            DocRecord(
                path=path,
                title=title,
                category=category,
                status=metadata.get("status", ""),
                owner_surface=metadata.get("owner_surface", ""),
                last_reviewed=metadata.get("last_reviewed", ""),
                canonical=metadata.get("canonical", ""),
            )
        )
    return records


def build_reference_records() -> list[DocRecord]:
    """Build canonical reference records for Markdown files under docs/references."""
    records: list[DocRecord] = []
    for path in sorted((DOCS_ROOT / "references").glob("*.md")):
        if path.name == "index.md":
            continue
        records.append(
            DocRecord(
                path=path,
                title=extract_title(path),
                category="reference",
                status="reference",
                owner_surface="repo",
                last_reviewed="",
                canonical="true",
            )
        )
    return records


def build_execplan_records(subdir: str, status: str) -> list[DocRecord]:
    """Build status-tagged records for every Markdown ExecPlan in one plan directory."""
    plan_dir = DOCS_ROOT / "exec-plans" / subdir
    records: list[DocRecord] = [
        DocRecord(
            path=path,
            title=parse_frontmatter(path).get("title") or extract_title(path),
            category=f"exec-plan-{subdir}",
            status=status,
            owner_surface="repo",
            last_reviewed="",
            canonical="true",
        )
        for path in sorted(plan_dir.glob("*.md"))
    ]
    return records


def rel_doc(path: Path) -> str:
    """Return a document path relative to the repository root."""
    return path.relative_to(ROOT).as_posix()


def render_section_index(title: str, intro: str, records: list[DocRecord]) -> str:
    """Render a generated category index that links each supplied document record."""
    lines = [GENERATED_COMMENT, "", f"# {title}", "", intro, ""]
    if not records:
        lines.extend(["No documents are currently indexed here.", ""])
        return "\n".join(lines).rstrip() + "\n"

    for record in records:
        lines.append(
            f"- [{record.title}](../{record.path.relative_to(DOCS_ROOT).as_posix()})"
        )
        if record.category in {"design-doc", "product-spec"}:
            lines.append(
                f"  - Status: `{record.status}` | Owner: `{record.owner_surface}` | "
                f"Last reviewed: `{record.last_reviewed}` | Canonical: `{record.canonical}`"
            )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_execplan_index(
    active: list[DocRecord], completed: list[DocRecord], tracker: Path
) -> str:
    """Render links for active and completed ExecPlans plus their supporting tracker."""
    lines = [
        GENERATED_COMMENT,
        "",
        "# Execution Plans",
        "",
        "Active and completed ExecPlans live here. The structure and required "
        "sections are defined in [`PLANS.md`](../../PLANS.md).",
        "",
        "## Active",
        "",
    ]
    if active:
        lines.extend(
            f"- [{record.title}](./active/{record.path.name})" for record in active
        )
    else:
        lines.append("- No active ExecPlans.")
    lines.extend(["", "## Completed", ""])
    if completed:
        lines.extend(
            f"- [{record.title}](./completed/{record.path.name})"
            for record in completed
        )
    else:
        lines.append("- No completed ExecPlans.")
    lines.extend(
        [
            "",
            "## Supporting Tracker",
            "",
            f"- [Tech Debt Tracker](./{tracker.name})",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_inventory(records: list[DocRecord]) -> str:
    """Render a Markdown table that inventories the supplied repository document records."""
    lines = [
        GENERATED_COMMENT,
        "",
        "# Repository Knowledge Inventory",
        "",
        "| Path | Title | Category | Status | Owner | Last Reviewed | Canonical |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        "| "
        + " | ".join(
            [
                f"`{rel_doc(record.path)}`",
                record.title.replace("|", "\\|"),
                f"`{record.category}`",
                f"`{record.status or '-'}`",
                f"`{record.owner_surface or '-'}`",
                f"`{record.last_reviewed or '-'}`",
                f"`{record.canonical or '-'}`",
            ]
        )
        + " |"
        for record in records
    )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def load_boundary_baseline() -> tuple[int, dict[str, int]]:
    """Return boundary-baseline totals and per-rule counts, or empty defaults when absent."""
    if not BOUNDARY_BASELINE_PATH.exists():
        return 0, {}
    payload = json.loads(BOUNDARY_BASELINE_PATH.read_text(encoding="utf-8"))
    violations = payload.get("violations", [])
    counts: dict[str, int] = {}
    for item in violations:
        rule_id = str(item.get("rule_id", "") or "")
        if not rule_id:
            continue
        counts[rule_id] = counts.get(rule_id, 0) + 1
    return len(violations), counts


def render_harness_health_report(
    *,
    design_records: list[DocRecord],
    product_records: list[DocRecord],
    reference_records: list[DocRecord],
    active_plans: list[DocRecord],
    completed_plans: list[DocRecord],
) -> str:
    """Render health metrics for document inventories, boundaries, and required runtime assets."""
    baseline_count, baseline_breakdown = load_boundary_baseline()
    lines = [
        GENERATED_COMMENT,
        "",
        "# Harness Health",
        "",
        *snapshot_provenance(),
        "",
        "This generated report summarizes the repository harness control plane.",
        "",
        "> Local snapshot of the working tree; it may be stale after edits or a branch switch.",
        "> Refresh with `python scripts/build_repo_knowledge_index.py --health-only`.",
        "> Asset status checks file existence, not test results or service health.",
        "",
        "## Knowledge System",
        "",
        f"- Design docs: `{len(design_records)}`",
        f"- Product specs: `{len(product_records)}`",
        f"- References: `{len(reference_records)}`",
        f"- Active ExecPlans: `{len(active_plans)}`",
        f"- Completed ExecPlans: `{len(completed_plans)}`",
        "",
        "## Boundary Baseline",
        "",
        f"- Baseline entries: `{baseline_count}`",
    ]
    if baseline_breakdown:
        for rule_id, count in sorted(baseline_breakdown.items()):
            lines.append(f"- `{rule_id}`: `{count}`")
    else:
        lines.append("- No boundary baseline has been recorded yet.")

    lines.extend(["", "## Critical Assets", ""])
    for path in REQUIRED_RUNTIME_ASSETS + REQUIRED_HARNESS_WORKFLOWS:
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"- {'OK' if path.exists() else 'MISSING'} `{rel}`")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_harness_health_report() -> str:
    """Build an optional health snapshot directly from the current working tree."""
    return render_harness_health_report(
        design_records=build_frontmatter_records(
            DOCS_ROOT / "design-docs", "design-doc"
        ),
        product_records=build_frontmatter_records(
            DOCS_ROOT / "product-specs", "product-spec"
        ),
        reference_records=build_reference_records(),
        active_plans=build_execplan_records("active", "active"),
        completed_plans=build_execplan_records("completed", "completed"),
    )


def build_knowledge_docs() -> dict[Path, str]:
    """Build version-controlled knowledge documents as a path-to-content mapping."""
    design_records = build_frontmatter_records(DOCS_ROOT / "design-docs", "design-doc")
    product_records = build_frontmatter_records(
        DOCS_ROOT / "product-specs", "product-spec"
    )
    reference_records = build_reference_records()
    active_plans = build_execplan_records("active", "active")
    completed_plans = build_execplan_records("completed", "completed")
    tracker = DOCS_ROOT / "exec-plans" / "tech-debt-tracker.md"

    all_records = build_tracked_records()

    documents = {
        DOCS_ROOT / "design-docs" / "index.md": render_section_index(
            "Design Docs",
            "Implementation and architecture decisions that shape repository "
            "behavior live here.",
            design_records,
        ),
        DOCS_ROOT / "product-specs" / "index.md": render_section_index(
            "Product Specs",
            "User-facing workflow and page behavior specifications live here.",
            product_records,
        ),
        DOCS_ROOT / "references" / "index.md": render_section_index(
            "References",
            "Evergreen repository references and operational guides live here.",
            reference_records,
        ),
        DOCS_ROOT / "exec-plans" / "index.md": render_execplan_index(
            active_plans, completed_plans, tracker
        ),
        DOCS_ROOT / "generated" / "doc-inventory.md": render_inventory(
            sorted(all_records, key=lambda record: rel_doc(record.path))
        ),
    }

    skills = focused_skills([record.path for record in all_records])
    for surface in ("api", "web"):
        directory = ROOT / "src" / surface / "skills"
        documents[directory / "README.md"] = render_skill_catalog(
            surface, [path for path in skills if path.parent.parent == directory]
        )
    return documents


def write_documents(*, health_only: bool = False) -> int:
    """Refresh the ignored health report and, by default, version-controlled indexes."""
    docs = {} if health_only else build_knowledge_docs()
    docs[HARNESS_HEALTH_PATH] = build_harness_health_report()
    for path, content in sorted(docs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(docs)} repository knowledge documents.")
    return 0


def main() -> int:
    """Regenerate knowledge documents or only the ignored local health report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--health-only",
        action="store_true",
        help="Refresh only docs/generated/harness-health.md without changing tracked indexes.",
    )
    args = parser.parse_args()
    return write_documents(health_only=args.health_only)


if __name__ == "__main__":
    raise SystemExit(main())
