#!/usr/bin/env python3
"""Validate the repository's agent-first harness layout."""

from __future__ import annotations

import json
import os
import posixpath
import re
import subprocess
import sys
import tempfile
import tomllib
from datetime import UTC, datetime
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

from build_repo_knowledge_index import (
    DOCS_ROOT,
    FRONTMATTER_FIELDS,
    REQUIRED_RUNTIME_ASSETS,
    build_knowledge_docs,
    focused_skills,
    parse_frontmatter,
    parse_review_date,
    tracked_markdown,
)
from build_repo_knowledge_index import (
    GENERATED_COMMENT as KNOWLEDGE_GENERATED_COMMENT,
)
from check_example_identifiers import find_violations as find_identifier_violations
from markdown_it import MarkdownIt

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_ROOT = ROOT / "src" / "web"
CODEX_ENVIRONMENT = ROOT / ".codex" / "environments" / "environment.toml"
FRONTEND_ENV_FILENAMES = (
    ".env",
    ".env.local",
    ".env.development",
    ".env.development.local",
    ".env.production",
    ".env.production.local",
    ".env.test",
    ".env.test.local",
)
STALE_FRONTEND_PATH = "src/" + "cook-web"
STALE_FRONTEND_PATH_PARTS = tuple(STALE_FRONTEND_PATH.split("/"))
STALE_FRONTEND_PATH_WHOLE_FILE_ALLOWLIST = {
    Path("docs/exec-plans/completed/rename-cook-web-directory.md"),
}
STALE_FRONTEND_PATH_LINE_ALLOWLIST = {
    Path(".github/workflows/prepare-release.yml"): {
        f'"legacy_path": "{STALE_FRONTEND_PATH}/package-lock.json",': 1,
    },
}
STALE_FRONTEND_PATH_CONTEXT_ALLOWLIST = {
    Path(".github/workflows/prepare-release.yml"): (
        "- name: Generate MarkdownFlow dependency changelog",
        '"name": "markdown-flow-ui",',
        '"path": "src/web/package-lock.json",',
        "def build_dependency_section",
    ),
}
BOUNDARY_BASELINE = DOCS_ROOT / "generated" / "architecture-boundary-baseline.json"
PR_REVIEW_SCOPE_MARKERS = (
    "one clearly defined problem",
    "correctly, safely, completely, and with adequate tests",
    "responsibility boundary",
)
COPILOT_REPOSITORY_AI_INSTRUCTIONS = ROOT / ".github" / "copilot-instructions.md"
REQUIRED_HEADINGS = ("Scope", "Do", "Avoid", "Commands", "Tests", "Related Skills")
RETIRED_GENERATED_MARKER = "<!-- Generated by scripts/generate_ai_collab_docs.py."
INSTRUCTION_MARKDOWN = MarkdownIt("commonmark")
# Inspect all link schemes instead of letting unsafe ones become plain text.
INSTRUCTION_MARKDOWN.validateLink = lambda _target: True
REMOTE_INSTRUCTION_SCHEMES = {"http", "https", "mailto"}
MANUAL_AGENTS = {
    ROOT / "AGENTS.md": (
        "ARCHITECTURE.md",
        "PLANS.md",
        "docs/engineering-baseline.md",
        "docs/exec-plans/active/",
        "docs/references/frontend-product-analytics.md",
        "Umami",
        *PR_REVIEW_SCOPE_MARKERS,
        "product analytics as a completion requirement",
        "best-effort",
        "python scripts/check_repo_harness.py",
        "python scripts/check_architecture_boundaries.py",
        "Do not add a `CLAUDE.md`",
        "docs/design-docs/ai-tool-compat.md",
        "pause the commit",
    ),
    ROOT / "src" / "api" / "AGENTS.md": (
        "../../ARCHITECTURE.md",
        "../../docs/engineering-baseline.md",
        "scripts/harness_diagnostics.py",
        "LiteLLM",
    ),
    ROOT / "src" / "web" / "AGENTS.md": (
        "../../ARCHITECTURE.md",
        "../../docs/engineering-baseline.md",
        "../../docs/references/frontend-product-analytics.md",
        "Umami",
        "new user-facing Cook Web capability or interaction path",
        "useTracking",
        "fail-open",
        "src/lib/request.ts",
        "npm run test:e2e",
    ),
    ROOT / ".github" / "AGENTS.md": (
        "../docs/engineering-baseline.md",
        "workflow trigger",
        "python scripts/check_repo_harness.py",
    ),
    ROOT / "docker" / "AGENTS.md": (
        "../docs/engineering-baseline.md",
        "docker-compose.dev.yml",
        "docker compose",
    ),
    ROOT / "scripts" / "AGENTS.md": (
        "../docs/engineering-baseline.md",
        "idempotent",
        "python scripts/check_repo_harness.py",
    ),
    ROOT / "src" / "api" / "flaskr" / "service" / "billing" / "AGENTS.md": (
        "billing_*",
        "credit_*",
        "order_orders",
        "service/order/payment_providers",
        "docs/design-docs/billing-subscription-design.md",
    ),
    ROOT / "src" / "api" / "flaskr" / "service" / "referral" / "AGENTS.md": (
        "referral_*",
        "auth_hooks.py",
        "referral_campaigns",
        "src/api/flaskr/service/billing",
    ),
}
SKIP_TREE_PARTS = {
    ".git",
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
}
REQUIRED_ROOT_DOCS = (
    ROOT / "ARCHITECTURE.md",
    ROOT / "PLANS.md",
    DOCS_ROOT / "README.md",
    DOCS_ROOT / "engineering-baseline.md",
    DOCS_ROOT / "QUALITY_SCORE.md",
    DOCS_ROOT / "RELIABILITY.md",
    DOCS_ROOT / "SECURITY.md",
    DOCS_ROOT / "exec-plans" / "tech-debt-tracker.md",
    DOCS_ROOT / "design-docs" / "agent-first-harness-phase-2.md",
    DOCS_ROOT / "design-docs" / "ai-tool-compat.md",
    DOCS_ROOT / "references" / "architecture-boundaries.md",
    DOCS_ROOT / "references" / "frontend-product-analytics.md",
    BOUNDARY_BASELINE,
)
REQUIRED_DOC_MARKERS = {
    DOCS_ROOT / "references" / "frontend-product-analytics.md": (
        "New UI Feature Requirement",
        "definition of done",
        "generic SPA pageview does not satisfy this requirement",
    ),
}
REQUIRED_DIRS = (
    DOCS_ROOT / "design-docs",
    DOCS_ROOT / "product-specs",
    DOCS_ROOT / "references",
    DOCS_ROOT / "generated",
    DOCS_ROOT / "exec-plans" / "active",
    DOCS_ROOT / "exec-plans" / "completed",
)
README_MARKERS = (
    "ARCHITECTURE.md",
    "PLANS.md",
    "design-docs/",
    "product-specs/",
    "references/",
    "exec-plans/active/",
    "generated/",
)
REQUIRED_WORKFLOWS = (
    ROOT / ".github" / "workflows" / "repo-harness.yml",
    ROOT / ".github" / "workflows" / "runtime-harness.yml",
    ROOT / ".github" / "workflows" / "harness-gardening.yml",
)


class InstructionHTMLParser(HTMLParser):
    """Identify HTML navigation attributes that bypass Markdown link tokens."""

    has_links = False

    def handle_starttag(self, _tag: str, attrs: list[tuple[str, str | None]]) -> None:
        """Flag navigation and resource attributes without fetching their values."""
        link_attributes = {
            "action",
            "data",
            "formaction",
            "href",
            "poster",
            "src",
            "srcdoc",
            "srcset",
            "xlink:href",
        }
        if any(name in link_attributes for name, _value in attrs):
            self.has_links = True


def check_ordered_headings(path: Path, text: str, errors: list[str]) -> None:
    """Check ordered headings."""
    positions: list[int] = []
    for heading in REQUIRED_HEADINGS:
        marker = f"## {heading}"
        index = text.find(marker)
        if index == -1:
            errors.append(f"Missing heading '{marker}' in {path}")
            return
        positions.append(index)
    if positions != sorted(positions):
        errors.append(f"Headings are out of order in {path}")


def check_generated_knowledge_docs(errors: list[str]) -> None:
    """Check generated knowledge docs."""
    expected_docs = build_knowledge_docs()
    for path, expected in sorted(expected_docs.items()):
        if not path.exists():
            errors.append(f"Missing generated knowledge doc: {path}")
            continue
        actual = path.read_text(encoding="utf-8")
        if KNOWLEDGE_GENERATED_COMMENT not in actual:
            errors.append(f"Missing generated knowledge marker in {path}")
        if actual != expected:
            errors.append(f"Generated knowledge doc is stale: {path}")


def check_instruction_content(
    path: Path, errors: list[str], *, required_local_link: Path | None = None
) -> str | None:
    """Validate repository-owned instructions and return their readable text."""
    try:
        if not path.resolve(strict=True).is_relative_to(ROOT.resolve()):
            errors.append(f"Instruction file leaves the repository: {path}")
            return None
        text = path.read_text(encoding="utf-8")
        required_destination = (
            required_local_link.resolve() if required_local_link is not None else None
        )
    except (OSError, UnicodeError, RuntimeError) as error:
        errors.append(f"Unable to read instruction file {path}: {error}")
        return None
    if not text.strip():
        errors.append(f"Empty instruction file: {path}")
    if RETIRED_GENERATED_MARKER in text:
        errors.append(f"Retired generated-instruction marker in {path}")
    tokens = INSTRUCTION_MARKDOWN.parse(text)
    found_required_link = required_destination is None
    while tokens:
        token = tokens.pop()
        # Image children form alt text, not navigable Markdown links.
        if token.type != "image":
            tokens.extend(token.children or [])
        if token.type in {"html_inline", "html_block"}:
            html = InstructionHTMLParser()
            html.feed(token.content)
            if html.has_links:
                errors.append(
                    f"Use Markdown links or images instead of raw HTML links in {path}"
                )
            continue
        if token.type not in {"link_open", "image"}:
            continue
        target = token.attrGet("href" if token.type == "link_open" else "src")
        if target is None:
            continue
        try:
            link = urlsplit(target)
        except ValueError as error:
            errors.append(f"Broken instruction link '{target}' in {path}: {error}")
            continue
        if link.scheme in REMOTE_INSTRUCTION_SCHEMES:
            continue
        decoded_path = unquote(link.path)
        if link.scheme or link.netloc or decoded_path.startswith(("//", "\\")):
            errors.append(f"Unsupported instruction link '{target}' in {path}")
            continue
        if not decoded_path:
            continue
        destination = (
            ROOT / decoded_path.lstrip("/")
            if decoded_path.startswith("/")
            else path.parent / decoded_path
        )
        try:
            destination = destination.resolve()
        except (OSError, RuntimeError, ValueError) as error:
            errors.append(f"Broken instruction link '{target}' in {path}: {error}")
            continue
        if not destination.is_relative_to(ROOT.resolve()):
            errors.append(
                f"Instruction link leaves the repository '{target}' in {path}"
            )
        elif not destination.exists():
            errors.append(f"Broken instruction link '{target}' in {path}")
        elif token.type == "link_open" and destination == required_destination:
            found_required_link = True
    if not found_required_link:
        errors.append(
            f"Instruction entry point must link to {required_local_link}: {path}"
        )
    return text


def check_instruction_files(errors: list[str]) -> None:
    """Validate instruction files without walking dependency or cache trees."""
    for directory, subdirs, filenames in os.walk(ROOT):
        subdirs[:] = sorted(name for name in subdirs if name not in SKIP_TREE_PARTS)
        for name in sorted(filenames):
            path = Path(directory) / name
            if name == "AGENTS.md":
                check_instruction_content(path, errors)


def check_compatibility_entry_points(errors: list[str]) -> None:
    """Keep the two compatibility entry points connected to shared instructions."""
    path = COPILOT_REPOSITORY_AI_INSTRUCTIONS
    if not path.is_file():
        errors.append(f"Missing Copilot instruction entry point: {path}")
    else:
        check_instruction_content(path, errors, required_local_link=ROOT / "AGENTS.md")
    gemini = ROOT / "GEMINI.md"
    try:
        valid_gemini = gemini.is_symlink() and gemini.resolve(strict=True) == (
            ROOT / "AGENTS.md"
        ).resolve(strict=True)
    except (OSError, RuntimeError):
        valid_gemini = False
    if not valid_gemini:
        errors.append(f"GEMINI.md must link to the root AGENTS.md: {gemini}")


def check_tracked_claude_instructions(errors: list[str]) -> None:
    """Reject shared Claude instructions while leaving personal files alone."""
    try:
        result = subprocess.run(
            [
                "git",
                "ls-files",
                "--cached",
                "-z",
                "--",
                ":(glob)**/CLAUDE.md",
                ":(glob)**/CLAUDE.local.md",
                ":(glob)**/.claude/rules/**/*.md",
            ],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        errors.append(f"Unable to enumerate tracked Claude instructions: {error}")
        return
    errors.extend(
        f"Unexpected tracked Claude instruction file: {os.fsdecode(path)}"
        for path in result.stdout.split(b"\0")
        if path
    )


def check_manual_agents(errors: list[str]) -> None:
    """Check required AGENTS entry points."""
    for path, markers in MANUAL_AGENTS.items():
        if not path.exists():
            errors.append(f"Missing required AGENTS file: {path}")
            continue
        text = check_instruction_content(path, errors)
        if text is None:
            continue
        check_ordered_headings(path, text, errors)
        errors.extend(
            f"Missing marker '{marker}' in {path}"
            for marker in markers
            if marker not in text
        )


def check_root_docs(errors: list[str]) -> None:
    """Check root docs."""
    errors.extend(
        f"Missing required root knowledge doc: {path}"
        for path in REQUIRED_ROOT_DOCS
        if not path.exists()
    )
    errors.extend(
        f"Missing required docs directory: {path}"
        for path in REQUIRED_DIRS
        if not path.exists()
    )
    for path, markers in REQUIRED_DOC_MARKERS.items():
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        errors.extend(
            f"Missing marker '{marker}' in {path}"
            for marker in markers
            if marker not in text
        )
    errors.extend(
        f"Missing required harness workflow: {path}"
        for path in REQUIRED_WORKFLOWS
        if not path.exists()
    )
    errors.extend(
        f"Missing required runtime harness asset: {path}"
        for path in REQUIRED_RUNTIME_ASSETS
        if not path.exists()
    )

    readme = DOCS_ROOT / "README.md"
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        errors.extend(
            f"Missing marker '{marker}' in {readme}"
            for marker in README_MARKERS
            if marker not in text
        )

    if (ROOT / "tasks.md").exists():
        errors.append("Repository-root tasks.md is retired and must not exist")

    if BOUNDARY_BASELINE.exists():
        text = BOUNDARY_BASELINE.read_text(encoding="utf-8")
        if '"version"' not in text or '"violations"' not in text:
            errors.append(f"Boundary baseline is malformed: {BOUNDARY_BASELINE}")


def _stale_path_is_in_allowed_context(
    relative_path: Path, lines: list[str], line_numbers: list[int]
) -> bool:
    """Keep an allowed stale path inside its owning workflow step."""
    context_markers = STALE_FRONTEND_PATH_CONTEXT_ALLOWLIST.get(relative_path)
    if not context_markers:
        return True

    step_starts = [
        index for index, line in enumerate(lines) if line.strip() == context_markers[0]
    ]
    if len(step_starts) != 1:
        return False

    step_start = step_starts[0]
    step_indent = len(lines[step_start]) - len(lines[step_start].lstrip())
    step_end = len(lines)
    for index in range(step_start + 1, len(lines)):
        line = lines[index]
        line_indent = len(line) - len(line.lstrip())
        if line_indent == step_indent and line.strip().startswith("- name:"):
            step_end = index
            break

    step_lines = lines[step_start:step_end]
    return all(
        any(marker in line for line in step_lines) for marker in context_markers
    ) and all(step_start <= line_number - 1 < step_end for line_number in line_numbers)


def _contains_stale_frontend_path(parts: tuple[str, ...]) -> bool:
    """Match the retired frontend path as complete path components."""
    return any(
        parts[index : index + len(STALE_FRONTEND_PATH_PARTS)]
        == STALE_FRONTEND_PATH_PARTS
        for index in range(len(parts) - len(STALE_FRONTEND_PATH_PARTS) + 1)
    )


def check_frontend_path_contract(errors: list[str]) -> None:
    """Require the current web frontend path and guard stale path additions."""
    if not FRONTEND_ROOT.is_dir():
        errors.append(f"Missing web frontend directory: {FRONTEND_ROOT}")

    try:
        result = subprocess.run(
            ["git", "ls-files", "--stage", "-z"],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        errors.append(f"Unable to enumerate tracked files for path validation: {error}")
        return

    for raw_path in result.stdout.split(b"\0"):
        if not raw_path:
            continue
        try:
            raw_metadata, raw_filename = raw_path.split(b"\t", 1)
            index_mode, object_id, _stage = raw_metadata.split(b" ", 2)
        except ValueError as error:
            errors.append(f"Unable to parse tracked file entry {raw_path!r}: {error}")
            continue

        relative_path = Path(raw_filename.decode("utf-8", errors="surrogateescape"))
        if _contains_stale_frontend_path(relative_path.parts):
            errors.append(f"Stale frontend path in tracked filename: {relative_path}")

        path = ROOT / relative_path
        if index_mode == b"160000":
            continue
        if index_mode == b"120000":
            try:
                symlink_target = subprocess.run(
                    ["git", "cat-file", "blob", object_id.decode("ascii")],
                    cwd=ROOT,
                    check=True,
                    capture_output=True,
                ).stdout.decode("utf-8", errors="surrogateescape")
            except (OSError, UnicodeError, subprocess.CalledProcessError) as error:
                errors.append(f"Unable to scan tracked symlink {path}: {error}")
                continue
            resolved_symlink_target = posixpath.normpath(
                posixpath.join(
                    relative_path.parent.as_posix(), symlink_target.rstrip("\n")
                )
            )
            if _contains_stale_frontend_path(Path(resolved_symlink_target).parts):
                errors.append(
                    f"Stale frontend path in tracked symlink target: "
                    f"{relative_path} -> {symlink_target}"
                )
            continue

        if relative_path in STALE_FRONTEND_PATH_WHOLE_FILE_ALLOWLIST:
            continue
        try:
            text = path.read_bytes().decode("utf-8", errors="surrogateescape")
        except OSError as error:
            errors.append(f"Unable to scan tracked file {path}: {error}")
            continue

        actual_occurrences: dict[str, int] = {}
        stale_line_numbers: list[int] = []
        for line_number, line in enumerate(text.splitlines(), start=1):
            if STALE_FRONTEND_PATH in line:
                stripped_line = line.strip()
                actual_occurrences[stripped_line] = (
                    actual_occurrences.get(stripped_line, 0) + 1
                )
                stale_line_numbers.append(line_number)
        expected_occurrences = STALE_FRONTEND_PATH_LINE_ALLOWLIST.get(relative_path, {})
        if actual_occurrences != expected_occurrences:
            errors.append(
                f"Unexpected stale frontend path occurrences in {path}: "
                f"expected {expected_occurrences}, got {actual_occurrences}"
            )
        elif not _stale_path_is_in_allowed_context(
            relative_path, text.splitlines(), stale_line_numbers
        ):
            errors.append(
                f"Allowed stale frontend path in {path} is outside its "
                "historical release lookup step"
            )


def check_frontend_runtime_contract(errors: list[str]) -> None:
    """Keep the frontend development and production entry points direct."""
    package_path = FRONTEND_ROOT / "package.json"
    try:
        package = json.loads(package_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        errors.append(f"Unable to load frontend package scripts: {error}")
        return

    scripts = package.get("scripts", {})
    expected_scripts = {
        "dev": "next dev --turbopack",
        "build": "next build",
    }
    for script_name, expected_command in expected_scripts.items():
        if scripts.get(script_name) != expected_command:
            errors.append(
                f"Frontend package script '{script_name}' must be '{expected_command}'"
            )

    run_web_path = ROOT / ".cursor" / "run-web.sh"
    try:
        run_web = run_web_path.read_text(encoding="utf-8")
    except OSError as error:
        errors.append(f"Unable to load Cursor frontend launcher: {error}")
        return
    if "exec npm run dev -- -H 0.0.0.0 -p 3000" not in run_web:
        errors.append(f"{run_web_path} must launch through 'npm run dev'")


def check_codex_frontend_asset_reuse(errors: list[str]) -> None:
    """Exercise current Codex source checkout asset reuse."""
    try:
        environment = tomllib.loads(CODEX_ENVIRONMENT.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        errors.append(f"Unable to load Codex environment config: {error}")
        return

    setup = environment.get("setup", {})
    current_frontend = Path("src") / "web"
    fixtures = (
        ("current assets", current_frontend, current_frontend, current_frontend),
    )

    for platform in ("darwin", "linux"):
        platform_setup = setup.get(platform, {})
        script = platform_setup.get("script")
        if not isinstance(script, str) or not script.strip():
            errors.append(
                f"Missing Codex {platform} setup script in {CODEX_ENVIRONMENT}"
            )
            continue

        for (
            fixture_name,
            env_directory,
            modules_directory,
            manifest_directory,
        ) in fixtures:
            with tempfile.TemporaryDirectory(
                prefix=f"ai-shifu-codex-{platform}-"
            ) as temporary_directory:
                fixture_root = Path(temporary_directory)
                source_tree = fixture_root / "source"
                worktree = fixture_root / "worktree"
                target_frontend = worktree / current_frontend
                target_frontend.mkdir(parents=True)

                lockfile_content = "compatible-lockfile\n"
                target_manifest = target_frontend / "package-lock.json"
                target_manifest.write_text(lockfile_content, encoding="utf-8")

                source_manifest = source_tree / manifest_directory / "package-lock.json"
                source_manifest.parent.mkdir(parents=True, exist_ok=True)
                source_manifest.write_text(lockfile_content, encoding="utf-8")

                source_envs: dict[str, Path] = {}
                source_env_modes: dict[str, int] = {}
                for env_filename in FRONTEND_ENV_FILENAMES:
                    source_env = source_tree / env_directory / env_filename
                    source_env.parent.mkdir(parents=True, exist_ok=True)
                    source_env.write_text(
                        f"FIXTURE={fixture_name}:{env_filename}\n", encoding="utf-8"
                    )
                    source_mode = 0o600 if env_filename.endswith(".local") else 0o640
                    source_env.chmod(source_mode)
                    source_envs[env_filename] = source_env
                    source_env_modes[env_filename] = source_mode

                source_modules = source_tree / modules_directory / "node_modules"
                source_modules.mkdir(parents=True, exist_ok=True)

                command_environment = os.environ.copy()
                command_environment.update(
                    {
                        "CODEX_SOURCE_TREE_PATH": str(source_tree),
                        "CODEX_WORKTREE_PATH": str(worktree),
                    }
                )
                try:
                    result = subprocess.run(
                        ["sh"],
                        cwd=worktree,
                        env=command_environment,
                        input=script,
                        text=True,
                        capture_output=True,
                        timeout=10,
                        check=False,
                    )
                except (OSError, subprocess.TimeoutExpired) as error:
                    errors.append(
                        f"Unable to run Codex {platform} {fixture_name} fixture: {error}"
                    )
                    continue

                fixture_label = f"Codex {platform} {fixture_name} fixture"
                if result.returncode != 0:
                    errors.append(
                        f"{fixture_label} failed with exit {result.returncode}: "
                        f"{result.stderr.strip()}"
                    )
                    continue

                for env_filename, source_env in source_envs.items():
                    target_env = target_frontend / env_filename
                    if not target_env.is_file() or target_env.read_text(
                        encoding="utf-8"
                    ) != source_env.read_text(encoding="utf-8"):
                        errors.append(
                            f"{fixture_label} did not copy the expected {env_filename}"
                        )
                        continue
                    if (
                        target_env.stat().st_mode & 0o777
                        != source_env_modes[env_filename]
                    ):
                        errors.append(
                            f"{fixture_label} did not preserve the mode of {env_filename}"
                        )

                target_modules = target_frontend / "node_modules"
                if not target_modules.is_symlink():
                    errors.append(
                        f"{fixture_label} did not reuse compatible node_modules"
                    )
                elif target_modules.resolve() != source_modules.resolve():
                    errors.append(
                        f"{fixture_label} reused node_modules from the wrong path"
                    )

                for occupancy_mode in ("customized", "dangling"):
                    occupied_worktree = fixture_root / f"{occupancy_mode}-worktree"
                    occupied_frontend = occupied_worktree / current_frontend
                    occupied_frontend.mkdir(parents=True)
                    (occupied_frontend / "package-lock.json").write_text(
                        lockfile_content, encoding="utf-8"
                    )
                    occupied_env = occupied_frontend / ".env"
                    occupied_env_link_target = None
                    if occupancy_mode == "customized":
                        occupied_env.write_text("CUSTOMIZED=1\n", encoding="utf-8")
                    else:
                        occupied_env.symlink_to(occupied_frontend / "missing.env")
                        occupied_env_link_target = occupied_env.readlink()

                    occupied_environment = command_environment.copy()
                    occupied_environment["CODEX_WORKTREE_PATH"] = str(occupied_worktree)
                    occupied_result = subprocess.run(
                        ["sh"],
                        cwd=occupied_worktree,
                        env=occupied_environment,
                        input=script,
                        text=True,
                        capture_output=True,
                        timeout=10,
                        check=False,
                    )
                    occupied_label = f"{fixture_label} {occupancy_mode} env fixture"
                    if occupied_result.returncode != 0:
                        errors.append(
                            f"{occupied_label} failed with exit "
                            f"{occupied_result.returncode}: "
                            f"{occupied_result.stderr.strip()}"
                        )
                        continue

                    for env_filename in FRONTEND_ENV_FILENAMES:
                        if env_filename == ".env":
                            continue
                        occupied_local_env = occupied_frontend / env_filename
                        if (
                            occupied_local_env.exists()
                            or occupied_local_env.is_symlink()
                        ):
                            errors.append(
                                f"{occupied_label} copied another frontend env file: "
                                f"{env_filename}"
                            )
                    if occupancy_mode == "customized":
                        if occupied_env.read_text(encoding="utf-8") != "CUSTOMIZED=1\n":
                            errors.append(
                                f"{occupied_label} overwrote the customized env file"
                            )
                    elif not occupied_env.is_symlink():
                        errors.append(
                            f"{occupied_label} did not preserve the dangling symlink"
                        )
                    elif occupied_env.readlink() != occupied_env_link_target:
                        errors.append(
                            f"{occupied_label} changed the dangling symlink target"
                        )


def check_frontmatter_docs(errors: list[str]) -> None:
    """Check frontmatter docs."""
    for category in ("design-docs", "product-specs"):
        for path in sorted((DOCS_ROOT / category).glob("*.md")):
            if path.name == "index.md":
                continue
            metadata = parse_frontmatter(path)
            errors.extend(
                f"Missing frontmatter field '{field}' in {path}"
                for field in FRONTMATTER_FIELDS
                if field not in metadata
                or (field != "last_reviewed" and not metadata[field])
            )


PLAN_HEADINGS = (
    "Purpose / Big Picture",
    "Progress",
    "Surprises & Discoveries",
    "Decision Log",
    "Outcomes & Retrospective",
    "Context and Orientation",
    "Plan of Work",
    "Concrete Steps",
    "Validation and Acceptance",
    "Idempotence and Recovery",
    "Interfaces and Dependencies",
)


def check_skill_metadata(paths: list[Path], errors: list[str]) -> None:
    """Reject undiscoverable or ambiguous focused skill metadata."""
    names: dict[str, Path] = {}
    for path in focused_skills(paths):
        metadata = parse_frontmatter(path)
        name, description = metadata.get("name", ""), metadata.get("description", "")
        if (
            not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name)
            or name != path.parent.name
        ):
            errors.append(f"Skill name must match its directory slug: {path}")
        if not description or description in {"|", ">", "|-", ">-"}:
            errors.append(f"Skill needs a nonempty description: {path}")
        if name in names:
            errors.append(f"Duplicate skill name {name}: {names[name]} and {path}")
        names[name] = path


def markdown_headings(text: str) -> set[str]:
    """Read actual section headings, excluding fenced code examples."""
    tokens = INSTRUCTION_MARKDOWN.parse(text)
    return {
        tokens[i + 1].content
        for i, token in enumerate(tokens)
        if token.type == "heading_open" and token.tag == "h2"
    }


def check_plan_lifecycle(
    paths: list[Path], errors: list[str], warnings: list[str]
) -> None:
    """Require usable plans and distinguish review reminders from archival."""
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        if not relative.startswith(
            ("docs/exec-plans/active/", "docs/exec-plans/completed/")
        ):
            continue
        text = path.read_text(encoding="utf-8")
        headings = markdown_headings(text)
        errors.extend(
            f"Missing ExecPlan section '{heading}': {path}"
            for heading in PLAN_HEADINGS
            if heading not in headings
        )
        pending = any(
            token.type == "inline" and re.match(r"^\[ \]\s", token.content)
            for token in INSTRUCTION_MARKDOWN.parse(text)
        )
        if path.parent.name == "completed" and pending:
            errors.append(f"Completed ExecPlan still has pending work: {path}")
        if path.parent.name == "active" and not pending:
            warnings.append(
                f"Active ExecPlan has no unchecked work; review scope and acceptance before archival: {path}"
            )


def check_review_dates(paths: list[Path], errors: list[str]) -> None:
    """Allow unknown review dates but reject invalid or future review claims."""
    for path in paths:
        if path.is_symlink():
            continue
        reviewed = parse_frontmatter(path).get("last_reviewed", "")
        if not reviewed:
            continue
        try:
            value = parse_review_date(reviewed)
        except ValueError:
            errors.append(f"Invalid last_reviewed date: {path}: {reviewed}")
            continue
        if value > datetime.now(UTC).date():
            errors.append(f"Future last_reviewed date: {path}: {reviewed}")


class DocumentHTMLLinks(HTMLParser):
    """Collect literal HTML links and anchors without interpreting JSX expressions."""

    def __init__(self) -> None:
        """Initialize per-document link and anchor state."""
        super().__init__()
        self.links: list[str] = []
        self.anchors: set[str] = set()

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        """Read static Markdown/MDX HTML attributes only."""
        for name, value in attrs:
            if not value or value.startswith("{"):
                continue
            if name == "id" or (tag == "a" and name == "name"):
                self.anchors.add(value)
            if (tag == "a" and name == "href") or (tag == "img" and name == "src"):
                self.links.append(value)


def document_navigation(path: Path) -> tuple[list[str], set[str]]:
    """Read real links and GitHub-style heading anchors, ignoring fenced examples."""
    tokens = INSTRUCTION_MARKDOWN.parse(path.read_text(encoding="utf-8"))
    html = DocumentHTMLLinks()
    links: list[str] = []
    slugs: set[str] = set()
    for index, token in enumerate(tokens):
        if token.type == "heading_open":
            heading = tokens[index + 1]
            label = "".join(
                child.content
                for child in heading.children or []
                if child.type in {"text", "code_inline", "image"}
            )
            base = re.sub(r"[^\w -]", "", label.lower()).replace(" ", "-")
            slug, counter = base, 0
            while slug in slugs:
                counter += 1
                slug = f"{base}-{counter}"
            slugs.add(slug)
        if token.type == "html_block":
            html.feed(token.content)
        for child in token.children or []:
            if child.type == "html_inline":
                html.feed(child.content)
            elif child.type in {"link_open", "image"}:
                links.append(
                    child.attrGet("href" if child.type == "link_open" else "src") or ""
                )
    return links + html.links, slugs | html.anchors


def check_local_document_links(paths: list[Path], errors: list[str]) -> None:
    """Validate local files and section links while exempting historical runtime paths."""
    anchors: dict[Path, set[str]] = {}
    for path in paths:
        if path.is_symlink():
            if not path.exists() or not path.resolve().is_relative_to(ROOT.resolve()):
                errors.append(f"Broken or external documentation alias: {path}")
            continue
        relative = path.relative_to(ROOT).as_posix()
        historical = relative.startswith(
            ("docs/history/", "docs/exec-plans/completed/")
        )
        links, _headings = document_navigation(path)
        for url in links:
            parsed = urlsplit(url)
            if parsed.scheme or parsed.netloc:
                continue
            target_path = unquote(parsed.path)
            target = (
                path
                if not target_path
                else ROOT / target_path.lstrip("/")
                if target_path.startswith("/")
                else path.parent / target_path
            ).resolve()
            if (
                historical
                and target.suffix.lower() not in {".md", ".mdx"}
                and not target.is_relative_to(DOCS_ROOT.resolve())
            ):
                # Historical implementation links may name retired code or assets.
                continue
            if not target.is_relative_to(ROOT.resolve()) or not target.exists():
                errors.append(f"Broken local document link: {path}: {url}")
                continue
            if parsed.fragment and target.suffix.lower() in {".md", ".mdx"}:
                if target not in anchors:
                    anchors[target] = document_navigation(target)[1]
                if unquote(parsed.fragment) not in anchors[target]:
                    errors.append(f"Broken local document anchor: {path}: {url}")


def check_partially_staged_documents(errors: list[str]) -> None:
    """Reject split document versions instead of validating unstaged fixes."""
    try:
        staged = subprocess.check_output(
            ["git", "diff", "--cached", "--name-only", "-z"], cwd=ROOT, text=True
        )
        unstaged = subprocess.check_output(
            ["git", "diff", "--name-only", "-z"], cwd=ROOT, text=True
        )
    except (OSError, subprocess.CalledProcessError) as error:
        errors.append(f"Unable to verify documentation staging: {error}")
        return
    partial = set(staged.split("\0")) & set(unstaged.split("\0"))
    errors.extend(
        f"Partially staged document: {name}. Stage the complete intended version "
        "or set aside its unstaged edits before validation; the harness reads "
        "working-tree contents and does not modify the index."
        for name in sorted(partial)
        if Path(name).suffix.lower() in {".md", ".mdx"}
    )


def check_documentation_contracts(errors: list[str], warnings: list[str]) -> None:
    """Check tracked sources separately from generated index freshness."""
    check_partially_staged_documents(errors)
    paths = tracked_markdown(ROOT)
    check_skill_metadata(paths, errors)
    check_plan_lifecycle(paths, errors, warnings)
    check_review_dates(paths, errors)
    check_local_document_links(paths, errors)


def check_example_identifiers(errors: list[str]) -> None:
    """Check example identifiers."""
    errors.extend(str(violation) for violation in find_identifier_violations())


def main() -> int:
    """Validate collaboration guidance and generated repository knowledge."""
    errors: list[str] = []
    check_generated_knowledge_docs(errors)
    check_instruction_files(errors)
    check_tracked_claude_instructions(errors)
    check_manual_agents(errors)
    check_compatibility_entry_points(errors)
    check_root_docs(errors)
    check_frontend_path_contract(errors)
    check_frontend_runtime_contract(errors)
    check_codex_frontend_asset_reuse(errors)
    check_frontmatter_docs(errors)
    check_example_identifiers(errors)
    warnings: list[str] = []
    check_documentation_contracts(errors, warnings)
    for warning in warnings:
        print(f"Review reminder: {warning}")

    if errors:
        print("Repository harness validation failed:", file=sys.stderr)
        for error in errors:
            print(f" - {error}", file=sys.stderr)
        return 1

    print("Repository harness validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
