#!/usr/bin/env python3
"""Generate module AGENTS.md files and thin Cursor/Copilot routing files."""

from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIDTH = 78
MIN_AGENT_LINES = 60
MAX_AGENT_LINES = 140
MAX_COMPAT_LINES = 40
REQUIRED_HEADINGS = (
    "Scope",
    "Do",
    "Avoid",
    "Commands",
    "Tests",
    "Related Skills",
)

DOC_COMMENT = (
    "<!-- Generated by scripts/generate_ai_collab_docs.py. "
    "Edit metadata in that script. -->"
)
INLINE_CODE_PATTERN = re.compile(r"`[^`]+`")
INLINE_CODE_SPACE = "\x07"


@dataclass(frozen=True)
class DocSpec:
    """Structured data for a generated AGENTS.md file."""

    title: str
    intro: str
    scope: tuple[str, ...]
    do: tuple[str, ...]
    avoid: tuple[str, ...]
    commands: tuple[str, ...]
    tests: tuple[str, ...]
    related_skills: tuple[str, ...]


@dataclass(frozen=True)
class BackendModuleMeta:
    """Compact metadata used to build backend service docs."""

    summary: str
    key_files: tuple[str, ...]
    invariants: tuple[str, ...]
    avoid_points: tuple[str, ...]
    tests_path: str
    tests_exist: bool
    skill_refs: tuple[str, ...] = ()
    owns_models: bool = True


@dataclass(frozen=True)
class FrontendDomainMeta:
    """Compact metadata used to build frontend subtree docs."""

    summary: str
    key_files: tuple[str, ...]
    invariants: tuple[str, ...]
    avoid_points: tuple[str, ...]
    test_focus: str
    skill_refs: tuple[str, ...] = ()


BACKEND_META = {
    "check_risk": BackendModuleMeta(
        summary=(
            "risk-control persistence and text moderation checks used to screen "
            "content before it proceeds through downstream flows"
        ),
        key_files=("funcs.py", "models.py"),
        invariants=(
            "keep moderation result persistence and provider interaction in the "
            "service helpers instead of scattering them across callers",
            "preserve business-key linkage between a risk decision and the "
            "content or request context that triggered it",
            "keep safe fallback behavior explicit when the upstream risk provider "
            "fails or times out",
        ),
        avoid_points=(
            "do not let routes or unrelated services call providers directly and "
            "skip this normalization layer",
            "do not store partial moderation records without the context needed "
            "to audit the decision later",
            "do not silently downgrade failure behavior without documenting the "
            "new risk posture in tests and task notes",
        ),
        tests_path="src/api/tests/service/check_risk/",
        tests_exist=False,
    ),
    "common": BackendModuleMeta(
        summary=(
            "shared backend DTOs, app exceptions, dictionaries, storage helpers, "
            "and other cross-service primitives"
        ),
        key_files=("dtos.py", "models.py", "dicts.py", "storage.py"),
        invariants=(
            "treat shared DTOs and app exceptions as compatibility surfaces used "
            "by many backend modules",
            "keep storage-provider selection and helper behavior centralized here "
            "instead of branching it in every service",
            "add new cross-service primitives here only when they are genuinely "
            "shared and not just convenient for one module",
        ),
        avoid_points=(
            "do not change shared DTO fields or exception codes without updating "
            "all consumers in the same task",
            "do not reimplement storage or dictionary helpers inside feature "
            "services when the shared layer should own them",
            "do not let this module become a grab bag for service-specific logic "
            "that belongs in a dedicated domain directory",
        ),
        tests_path="src/api/tests/service/common/",
        tests_exist=True,
        owns_models=False,
    ),
    "config": BackendModuleMeta(
        summary=(
            "persisted application configuration, encryption helpers, and cached "
            "backend configuration access"
        ),
        key_files=("funcs.py", "models.py"),
        invariants=(
            "route reads and writes through the config helper functions so "
            "encryption, caching, and locking stay consistent",
            "preserve the contract between database-backed config values and "
            "environment-driven defaults in `flaskr.common.config`",
            "keep sensitive values encrypted at rest and invalidate caches when "
            "writes happen",
        ),
        avoid_points=(
            "do not read or write encrypted config rows directly from unrelated "
            "services when helper functions already own that behavior",
            "do not add new config keys without updating env metadata or "
            "documentation where the value is expected",
            "do not bypass cache-key and lock-key helpers when changing config "
            "persistence behavior",
        ),
        tests_path="src/api/tests/service/config/",
        tests_exist=True,
    ),
    "dashboard": BackendModuleMeta(
        summary=(
            "dashboard reporting routes, DTOs, and aggregate metrics for admin "
            "and course-level reporting surfaces"
        ),
        key_files=("routes.py", "funcs.py", "dtos.py"),
        invariants=(
            "keep dashboard DTO shapes stable because frontend admin pages depend "
            "on the serialized field names and formatting",
            "preserve centralized money, ratio, and percentage formatting in the "
            "dashboard helper layer",
            "treat dashboard queries as reporting logic with access-control "
            "expectations, not as general-purpose business mutations",
        ),
        avoid_points=(
            "do not move formatting logic into routes or frontend pages when the "
            "backend DTO contract already defines the presentation shape",
            "do not add heavy reporting queries without checking query scope, "
            "pagination, and filter defaults",
            "do not widen dashboard data access without preserving existing "
            "permission or audience assumptions",
        ),
        tests_path="src/api/tests/service/dashboard/",
        tests_exist=True,
        owns_models=False,
    ),
    "feedback": BackendModuleMeta(
        summary=(
            "user feedback submission persistence and helper logic for collecting "
            "qualitative product feedback"
        ),
        key_files=("funs.py", "models.py"),
        invariants=(
            "keep feedback submission validation close to the persistence helper "
            "so callers do not invent divergent checks",
            "preserve the link between feedback content, user identity, and any "
            "optional contact information captured with the report",
            "treat this service as a write-oriented boundary and add explicit "
            "query helpers before expanding read behavior",
        ),
        avoid_points=(
            "do not duplicate feedback persistence logic in route handlers or "
            "frontend adapters",
            "do not accept new feedback payload fields without updating storage, "
            "validation, and any downstream notifications together",
            "do not ignore the existing file naming quirk of `funs.py`; follow "
            "local structure unless you are deliberately refactoring it",
        ),
        tests_path="src/api/tests/service/feedback/",
        tests_exist=False,
    ),
    "learn": BackendModuleMeta(
        summary=(
            "learning-session orchestration, SSE streaming, ask-provider "
            "adapters, listen-mode assembly, and runtime conversation state"
        ),
        key_files=(
            "routes.py",
            "learn_funcs.py",
            "runscript_v2.py",
            "listen_element_run_stream.py",
            "ask_provider_adapters/registry.py",
        ),
        invariants=(
            "preserve the SSE event flow and element-oriented runtime state used "
            "by study, preview, and listen-mode frontends",
            "keep ask-provider integration behind adapter and registry layers so "
            "provider-specific branches do not leak into routes",
            "treat listen-mode and preview helpers as part of the same runtime "
            "state machine, and update them together when payload contracts move",
        ),
        avoid_points=(
            "do not introduce a second streaming protocol or event naming scheme "
            "without updating every consumer and compatibility path",
            "do not bypass adapter normalization when wiring new provider or "
            "workflow integrations into ask flows",
            "do not change runtime DTO enums or element semantics without "
            "coordinated frontend and test updates",
        ),
        tests_path="src/api/tests/service/learn/",
        tests_exist=True,
        owns_models=True,
    ),
    "llm": BackendModuleMeta(
        summary=(
            "thin LLM-facing HTTP route registration that should stay aligned "
            "with the shared LiteLLM integration layer"
        ),
        key_files=("route.py",),
        invariants=(
            "treat `src/api/flaskr/api/llm/__init__.py` as the shared provider "
            "integration layer and keep this service route-focused",
            "preserve OpenAI-compatible request and response expectations when "
            "proxying provider traffic",
            "add provider-specific behavior only when the shared wrapper cannot "
            "reasonably absorb it",
        ),
        avoid_points=(
            "do not duplicate LiteLLM or provider-registration logic in this "
            "service subtree",
            "do not couple route behavior tightly to one vendor when multiple "
            "OpenAI-compatible providers must coexist",
            "do not expose provider secrets, base URLs, or unsupported internal "
            "error details in API responses",
        ),
        tests_path="src/api/tests/service/llm/",
        tests_exist=False,
        owns_models=False,
    ),
    "metering": BackendModuleMeta(
        summary=(
            "usage recording, usage reporting routes, and normalization constants "
            "for billable LLM and TTS activity"
        ),
        key_files=("routes.py", "recorder.py", "consts.py", "models.py"),
        invariants=(
            "normalize usage types, scenes, and billable flags in the shared "
            "consts and recorder helpers before persisting records",
            "keep recorder helpers as the single place that translates runtime "
            "events into persisted metering rows",
            "preserve reporting filters and date parsing behavior exposed through "
            "the metering routes",
        ),
        avoid_points=(
            "do not let callers write metering rows directly when recorder "
            "helpers already own the normalization contract",
            "do not introduce new usage-scene semantics without updating both "
            "const normalization and reporting expectations",
            "do not change billable defaults or record structure without checking "
            "downstream finance or quota consumers",
        ),
        tests_path="src/api/tests/service/metering/",
        tests_exist=True,
    ),
    "order": BackendModuleMeta(
        summary=(
            "orders, payment-provider integration, coupon handling, admin order "
            "surfaces, and related payment workflows"
        ),
        key_files=(
            "funs.py",
            "models.py",
            "coupon_funcs.py",
            "admin.py",
            "payment_providers/base.py",
        ),
        invariants=(
            "keep payment-provider differences behind the provider abstraction "
            "layer instead of branching through every order flow",
            "preserve idempotent order, coupon, and payment-notification "
            "handling because retries are normal in payment systems",
            "when legacy provider raw tables are shared with billing snapshots, "
            "keep legacy `/order` reads and writes scoped to "
            "`biz_domain='order'`",
            "treat admin DTOs and public order payloads as compatibility "
            "surfaces used outside this module",
        ),
        avoid_points=(
            "do not wire new payment gateways directly into routes or business "
            "helpers without extending the provider abstraction",
            "do not split discount, coupon, and order-state transitions across "
            "multiple places where rollback behavior becomes unclear",
            "do not change payment callback handling without explicit tests for "
            "duplicate or out-of-order notifications",
        ),
        tests_path="src/api/tests/service/order/",
        tests_exist=True,
    ),
    "profile": BackendModuleMeta(
        summary=(
            "profile-variable definitions, value persistence, profile mapping, "
            "and profile route handling"
        ),
        key_files=("routes.py", "funcs.py", "models.py", "profile_manage.py"),
        invariants=(
            "preserve the mapping between profile variables, stored values, and "
            "derived aggregate fields updated for users",
            "keep route payloads, DTOs, and persistence helpers in sync when "
            "profile definitions evolve",
            "treat profile schema and value semantics as shared data contracts "
            "used by authoring and runtime flows",
        ),
        avoid_points=(
            "do not update profile values in ad-hoc code paths that bypass the "
            "aggregation and normalization helpers",
            "do not rename variable mappings or profile DTO fields without "
            "coordinated frontend and backend updates",
            "do not spread profile-definition constants across unrelated modules "
            "when this service already owns them",
        ),
        tests_path="src/api/tests/service/profile/",
        tests_exist=True,
    ),
    "promo": BackendModuleMeta(
        summary=(
            "promotion campaigns, coupon and redemption models, and promo "
            "application or rollback logic tied to order lifecycles"
        ),
        key_files=("funcs.py", "models.py", "consts.py"),
        invariants=(
            "keep promo application, rollback, and redemption behavior "
            "idempotent with respect to order retries and timeout recovery",
            "preserve centralized discount calculation inside promo helpers so "
            "coupon math does not drift across callers",
            "treat campaign and redemption rows as audit records that should stay "
            "coherent when business rules evolve",
        ),
        avoid_points=(
            "do not split promo rollback logic between order code and promo code "
            "in ways that make eventual state ambiguous",
            "do not duplicate discount calculations or eligibility filters in "
            "frontend code or neighboring services",
            "do not change redemption semantics without reviewing order and "
            "coupon interactions together",
        ),
        tests_path="src/api/tests/service/promo/",
        tests_exist=False,
    ),
    "resource": BackendModuleMeta(
        summary=(
            "resource metadata and resource-usage persistence, currently centered "
            "on the service data model layer"
        ),
        key_files=("models.py",),
        invariants=(
            "keep resource and usage records aligned with business-key and index "
            "conventions because other modules may read them indirectly",
            "treat this directory as a data-model boundary until explicit "
            "service helpers or routes are introduced",
            "add new query or mutation helpers here instead of scattering raw "
            "resource table access through unrelated services",
        ),
        avoid_points=(
            "do not let other modules invent incompatible meanings for resource "
            "rows or usage rows without updating the owning models",
            "do not grow hidden behavior in compiled artifacts or untracked files "
            "when the checked-in model layer is the source of truth",
            "do not skip migration review when resource columns or indexes move",
        ),
        tests_path="src/api/tests/service/resource/",
        tests_exist=False,
    ),
    "shifu": BackendModuleMeta(
        summary=(
            "core shifu authoring, outline structure, draft history, publish, "
            "import/export, permissions, and resource-link management"
        ),
        key_files=(
            "route.py",
            "funcs.py",
            "models.py",
            "permissions.py",
            "shifu_history_manager.py",
        ),
        invariants=(
            "preserve the separation between draft state, publish state, and "
            "history logs so authoring recovery remains trustworthy",
            "keep outline and structural mutations going through the dedicated "
            "shifu helper modules instead of ad-hoc tree edits",
            "treat import/export, ask-provider config, and permissions as "
            "cross-cutting contracts that need coordinated updates",
        ),
        avoid_points=(
            "do not mutate outline structures directly from route handlers when "
            "the shifu helper modules already own those transitions",
            "do not change publish or import/export payload shapes without "
            "updating related history and validation behavior together",
            "do not bypass permission checks when adding authoring or admin "
            "operations in this module",
        ),
        tests_path="src/api/tests/service/shifu/",
        tests_exist=True,
        skill_refs=("src/api/skills/shifu-authoring-flow/SKILL.md",),
    ),
    "tts": BackendModuleMeta(
        summary=(
            "text-to-speech validation, segmentation, streaming, provider "
            "pipeline orchestration, and usage recording"
        ),
        key_files=(
            "__init__.py",
            "pipeline.py",
            "streaming_tts.py",
            "validation.py",
            "tts_usage_recorder.py",
        ),
        invariants=(
            "validate TTS settings strictly before provider calls so malformed "
            "requests fail early and predictably",
            "preserve the boundary and stripping helpers that keep partial "
            "markdown, XML, or media fragments from breaking streams",
            "record TTS usage through the shared recorder path so metering stays "
            "consistent with generated audio behavior",
        ),
        avoid_points=(
            "do not fork request validation or segmentation logic into multiple "
            "entry points where behavior can drift",
            "do not change streaming chunk semantics without checking both the "
            "runtime pipeline and usage-recorder expectations",
            "do not skip metering updates when new TTS paths or providers are "
            "introduced in the pipeline",
        ),
        tests_path="src/api/tests/service/tts/",
        tests_exist=True,
    ),
    "user": BackendModuleMeta(
        summary=(
            "user records, auth credentials, verification-code flows, token "
            "storage, temp-user handling, and auth-provider integration"
        ),
        key_files=(
            "user.py",
            "repository.py",
            "models.py",
            "auth/factory.py",
            "email_flow.py",
        ),
        invariants=(
            "keep credential lookup, token persistence, and provider dispatch in "
            "the shared repository and auth-factory paths",
            "preserve verification-code consumption rules and temp-user semantics "
            "so auth retries do not create inconsistent user state",
            "treat auth payloads, token fields, and credential models as shared "
            "contracts used by frontend login flows and backend guards",
        ),
        avoid_points=(
            "do not bypass repository or token-store helpers when touching auth "
            "state, credential persistence, or verification flows",
            "do not add provider-specific branches to every caller when the auth "
            "factory should own that dispatch logic",
            "do not change user identifiers, avatar handling, or code-consumption "
            "rules without coordinated tests for retries and error paths",
        ),
        tests_path="src/api/tests/service/user/",
        tests_exist=True,
        skill_refs=("src/api/skills/user-auth-flows/SKILL.md",),
    ),
}

FRONTEND_META = {
    "app": FrontendDomainMeta(
        summary=(
            "Next.js App Router entry points, route-group layouts, route handlers, "
            "and page-level composition for learner, admin, and legal surfaces"
        ),
        key_files=("layout.tsx", "page.tsx", "admin/layout.tsx", "c/layout.tsx"),
        invariants=(
            "keep route entry concerns in App Router files and move reusable logic "
            "into components, hooks, stores, or `lib/` when it spreads",
            "preserve route-parameter handling, redirect behavior, and metadata "
            "semantics across both the modern and legacy route groups",
            "treat app-route changes as integration changes that may affect auth, "
            "request bootstrapping, and shared providers",
        ),
        avoid_points=(
            "do not embed large business helpers directly in `page.tsx` files when "
            "they belong in shared modules",
            "do not fork learner and admin route logic unless product behavior "
            "really diverges",
            "do not hardcode route parsing when shared URL or state helpers "
            "already exist in the frontend codebase",
        ),
        test_focus="src/web/src/app/",
        skill_refs=(
            "src/web/skills/deep-link-lessonid-routing/SKILL.md",
            "src/web/skills/chat-layout-width-detection/SKILL.md",
        ),
    ),
    "api": FrontendDomainMeta(
        summary=(
            "thin endpoint definition wrappers that expose Cook Web API calls on "
            "top of the shared request and generated-client helpers"
        ),
        key_files=("api.ts", "index.ts", "user.ts", "course.ts", "studyV2.ts"),
        invariants=(
            "preserve learner request payloads and stream contracts alongside generated endpoint wrappers",
            "keep this layer declarative and thin so endpoint wiring stays easy to "
            "audit against backend contracts",
            "prefer the shared `lib/request.ts` and `lib/api.ts` stack instead of "
            "creating per-endpoint fetch wrappers here",
            "treat exported API functions as compatibility surfaces consumed by "
            "pages, hooks, and stores across the app",
        ),
        avoid_points=(
            "do not add ad-hoc response-shape parsing here when centralized "
            "business-code handling already exists lower in the stack",
            "do not duplicate route constants or auth-header behavior that belongs "
            "in shared request utilities",
            "do not duplicate endpoint wrappers or change learner request shapes "
            "while reorganizing API modules",
        ),
        test_focus="src/web/src/api/",
        skill_refs=("src/web/skills/deep-link-lessonid-routing/SKILL.md",),
    ),
    "components": FrontendDomainMeta(
        summary=(
            "shared React UI and business components used across learner, admin, "
            "auth, settings, preview, and chat-oriented experiences"
        ),
        key_files=("auth/EmailLogin.tsx", "shifu-edit/ShifuEdit.tsx", "ui/Button.tsx"),
        invariants=(
            "preserve learner mobile, modal, branding, and chat styling and props when moving shared components",
            "keep user-facing strings routed through shared i18n and component "
            "props instead of hardcoded labels",
            "preserve stable component contracts for callers before making broad "
            "prop or state-shape changes",
            "treat chat, preview, and auth components as shared behavior that "
            "often needs coordinated store and skill updates",
        ),
        avoid_points=(
            "do not hide domain logic in styling-only components when the behavior "
            "belongs in hooks, stores, or shared libs",
            "do not add one-off request logic inside components that should call "
            "shared API helpers",
            "do not copy interaction or streaming behavior between components when "
            "an existing shared component or skill already describes it",
        ),
        test_focus="src/web/src/components/",
        skill_refs=(
            "src/web/skills/chat-element-streaming/SKILL.md",
            "src/web/skills/chat-actionbar-ask-placement/SKILL.md",
            "src/web/skills/listen-mode-audio-streaming/SKILL.md",
        ),
    ),
    "config": FrontendDomainMeta(
        summary=(
            "frontend runtime environment helpers and supporting documentation for "
            "browser-visible configuration"
        ),
        key_files=("environment.ts", "ENVIRONMENT_CONFIG.md"),
        invariants=(
            "keep browser-safe environment reads centralized so pages and "
            "components do not branch on raw process variables",
            "preserve the contract between backend `/api/config` output and local "
            "environment defaults consumed on the frontend",
            "treat configuration docs as part of the public developer interface "
            "for Cook Web setup and troubleshooting",
        ),
        avoid_points=(
            "do not scatter environment parsing across components or hooks when "
            "`environment.ts` should stay the source of truth",
            "do not expose secrets or server-only config values in frontend code "
            "or docs",
            "do not let docs drift from runtime behavior when adding or removing "
            "frontend configuration flags",
        ),
        test_focus="src/web/src/config/",
    ),
    "hooks": FrontendDomainMeta(
        summary=(
            "shared React hooks for auth, audio coordination, and other reusable "
            "frontend behavior"
        ),
        key_files=(
            "useAuth.ts",
            "useExclusiveAudio.ts",
            "useGoogleAuth.ts",
            "useToast.tsx",
        ),
        invariants=(
            "keep business events on useTracking and delegate Umami transport to lib/tracking.ts",
            "keep hook inputs and returned fields stable, and update all consumers "
            "in the same task when the contract changes",
            "preserve browser and server assumptions explicitly so hooks do not "
            "accidentally run client-only code on the server",
            "treat hooks as reusable orchestration layers that should call shared "
            "stores and libs instead of duplicating low-level logic",
        ),
        avoid_points=(
            "do not leave partially renamed hook return fields in consumers after "
            "a contract refactor",
            "do not hide API calls or state transitions in hooks without keeping "
            "the underlying shared utilities testable",
            "do not couple hooks to one page or one route if the behavior should "
            "stay generally reusable",
        ),
        test_focus="src/web/src/hooks/",
        skill_refs=("src/web/skills/hook-contract-refactor-safety/SKILL.md",),
    ),
    "lib": FrontendDomainMeta(
        summary=(
            "shared frontend infrastructure such as request handling, generated "
            "API wrappers, i18n helpers, normalization, and testable utility code"
        ),
        key_files=(
            "request.ts",
            "api.ts",
            "shifu-normalize.ts",
            "unified-i18n-backend.ts",
        ),
        invariants=(
            "keep raw Umami calls in tracking.ts; preserve identify, queue, drain, SPA pageview deduplication, and tracked-referrer ordering",
            "keep analytics fail-open and accept only approved flat scalar fields; truncation or hashing does not make sensitive data safe",
            "preserve shared URL, interaction, lesson-feedback, audio, and storage semantics when changing helpers",
            "keep request transport, business-code handling, and shared API "
            "generation logic centralized in this domain",
            "preserve shared normalization and utility behavior used by multiple "
            "pages, hooks, or stores before changing payload assumptions",
            "treat this directory as the right home for cross-cutting frontend "
            "logic that should not live inside route components",
        ),
        avoid_points=(
            "do not move request or auth-header behavior into pages or components "
            "when `lib/request.ts` already owns that path",
            "do not reimplement shared normalization helpers in feature code when "
            "they belong here",
            "do not change shared utility contracts without rerunning affected "
            "tests and type checks across consumers",
        ),
        test_focus="src/web/src/lib/",
        skill_refs=(
            "src/web/skills/module-augmentation-guardrails/SKILL.md",
            "src/web/skills/deep-link-lessonid-routing/SKILL.md",
            "src/web/skills/interaction-user-input-defaults/SKILL.md",
            "src/web/skills/listen-mode-audio-streaming/SKILL.md",
        ),
    ),
    "store": FrontendDomainMeta(
        summary=(
            "shared frontend stores, store providers, and app-level state "
            "containers used by auth, i18n loading, and shifu flows"
        ),
        key_files=(
            "useUserStore.ts",
            "useShifu.tsx",
            "useI18nLoadingStore.ts",
            "userProvider.tsx",
        ),
        invariants=(
            "preserve course, environment, system, and layout state semantics across learner and teacher consumers; use direct module imports inside store implementations to avoid barrel cycles",
            "keep store state shape and exported actions stable because many "
            "components depend on these slices implicitly",
            "preserve the boundary between store state and side-effect helpers so "
            "persistent logic stays testable",
            "treat auth token handling and global providers as integration points "
            "shared across the whole frontend",
        ),
        avoid_points=(
            "do not add page-specific derived state here when a local hook or "
            "component can own it safely",
            "do not rename store fields without updating all selectors and hooks "
            "in the same task",
            "do not duplicate token or session storage behavior outside the "
            "existing user-store path",
        ),
        test_focus="src/web/src/store/",
        skill_refs=(
            "src/web/skills/hook-contract-refactor-safety/SKILL.md",
            "src/web/skills/chat-layout-width-detection/SKILL.md",
        ),
    ),
    "types": FrontendDomainMeta(
        summary=(
            "shared TypeScript declarations, ambient module definitions, and "
            "cross-domain frontend interfaces"
        ),
        key_files=(
            "shifu.ts",
            "store.ts",
            "sse.d.ts",
            "markdown-flow-ui.d.ts",
            "i18n-keys.d.ts",
        ),
        invariants=(
            "treat shared type exports as compatibility surfaces consumed across "
            "routes, stores, hooks, and components",
            "keep ambient declarations and module augmentation narrow so upstream "
            "package exports are not accidentally shadowed",
            "prefer updating source types together with their consumers instead of "
            "papering over mismatches with broad `any` casts",
        ),
        avoid_points=(
            "do not replace an upstream module declaration wholesale when a small "
            "augmentation would be safer",
            "do not leave stale declaration files after refactors that move or "
            "rename shared types",
            "do not solve runtime-shape drift only in type files without fixing "
            "the owning implementation",
        ),
        test_focus="src/web/src/types/",
        skill_refs=("src/web/skills/module-augmentation-guardrails/SKILL.md",),
    ),
    "constants": FrontendDomainMeta(
        summary=(
            "shared course and UI constants used across learner and teacher flows"
        ),
        key_files=("uiConstants.ts", "courseConstants.ts"),
        invariants=(
            "keep shared breakpoint, course, and UI constants as the "
            "single source of truth for all consumers",
            "preserve constant names and semantics when skills or stores already "
            "depend on them indirectly",
            "treat this directory as configuration data rather than a place to "
            "hide behavior that belongs in hooks or services",
        ),
        avoid_points=(
            "do not duplicate breakpoints or query-parameter constants in legacy "
            "pages when they already exist here",
            "do not mix runtime branching logic into constant files unless the "
            "logic is truly configuration-oriented",
            "do not rename exported constants casually because many files "
            "import them directly",
        ),
        test_focus="src/web/src/constants/",
        skill_refs=("src/web/skills/chat-layout-width-detection/SKILL.md",),
    ),
    "lib/shifu": FrontendDomainMeta(
        summary=(
            "course business orchestration for shifu and state transform helpers "
            "consumed by learner flows and shared stores"
        ),
        key_files=("Shifu.ts", "shifuUtils.ts", "storeUtil.ts"),
        invariants=(
            "keep course business transformations centralized so `c` pages and "
            "stores do not all reshape the same payloads differently",
            "preserve compatibility with `api` response shapes and `store` "
            "state expectations when business behavior changes",
            "treat this subtree as the right place for course orchestration, not "
            "for low-level request or UI-only helpers",
        ),
        avoid_points=(
            "do not duplicate shifu or state transformations in pages when "
            "this service layer already owns them",
            "do not change compatibility behavior while reorganizing shared code",
            "do not change service outputs without updating dependent stores and "
            "pages together",
        ),
        test_focus="src/web/src/lib/shifu/",
        skill_refs=(
            "src/web/skills/chat-element-streaming/SKILL.md",
            "src/web/skills/interaction-user-input-defaults/SKILL.md",
        ),
    ),
}


AGENTS_ONLY_POINTER = (
    "Read the nearest `AGENTS.md` first. It is the only project-instruction "
    "body. Do not duplicate hard rules here.",
    "Do not add a `CLAUDE.md` file. Claude-only path rules belong in `.claude/rules/`.",
)
CURSOR_PRIVATE_POINTER = (
    "Keep this file limited to Cursor-private routing that `AGENTS.md` cannot "
    "express: globs, `alwaysApply`, and the description.",
)
COPILOT_PRIVATE_POINTER = (
    "Keep this file limited to Copilot path routing via `applyTo`. Prefer "
    "native `AGENTS.md` for Copilot coding agent.",
)
PATH_AGENTS_POINTER = (
    "Follow the nearest subtree `AGENTS.md` for path-specific rules.",
)


def wrap_bullet(text: str) -> list[str]:
    """Wrap one markdown bullet item."""
    return wrap_markdown(text, initial_indent="- ", subsequent_indent="  ")


def wrap_paragraph(text: str) -> list[str]:
    """Wrap a plain paragraph."""
    return wrap_markdown(text)


def protect_inline_code(text: str) -> str:
    """Replace spaces inside inline-code spans so wrapping keeps them intact."""
    return INLINE_CODE_PATTERN.sub(
        lambda match: match.group(0).replace(" ", INLINE_CODE_SPACE),
        text,
    )


def wrap_markdown(
    text: str,
    *,
    initial_indent: str = "",
    subsequent_indent: str = "",
) -> list[str]:
    """Wrap Markdown while keeping inline-code spans on one line."""
    protected = protect_inline_code(text)
    wrapped = textwrap.fill(
        protected,
        width=WIDTH,
        initial_indent=initial_indent,
        subsequent_indent=subsequent_indent,
        break_long_words=False,
        break_on_hyphens=False,
    )
    return [line.replace(INLINE_CODE_SPACE, " ") for line in wrapped.splitlines()]


def sentence_case(text: str) -> str:
    """Normalize a metadata fragment into a sentence-like bullet."""
    normalized = text.strip()
    if not normalized:
        return normalized
    normalized = normalized[0].upper() + normalized[1:]
    if normalized[-1] not in ".!?":
        normalized += "."
    return normalized


def render_section(heading: str, items: tuple[str, ...]) -> list[str]:
    """Render a markdown section with wrapped bullets."""
    lines = [f"## {heading}", ""]
    for item in items:
        lines.extend(wrap_bullet(item))
        lines.append("")
    return lines


def render_agents(spec: DocSpec) -> str:
    """Render one AGENTS.md file."""
    lines = [DOC_COMMENT, "", f"# {spec.title}", ""]
    lines.extend(wrap_paragraph(spec.intro))
    lines.append("")
    lines.extend(render_section("Scope", spec.scope))
    lines.extend(render_section("Do", spec.do))
    lines.extend(render_section("Avoid", spec.avoid))
    lines.extend(render_section("Commands", spec.commands))
    lines.extend(render_section("Tests", spec.tests))
    lines.extend(render_section("Related Skills", spec.related_skills))
    return "\n".join(lines).rstrip() + "\n"


def join_paths(*paths: str) -> str:
    """Format a list of relative paths for display."""
    return ", ".join(f"`{path}`" for path in paths)


def maybe_tests_note(meta: BackendModuleMeta) -> str:
    """Describe the expected pytest location."""
    if meta.tests_exist:
        return f"`{meta.tests_path}` already exists and should remain the first stop."
    return (
        f"`{meta.tests_path}` does not exist yet; create it when this service gains "
        "or changes behavior."
    )


def backend_test_command(meta: BackendModuleMeta) -> str:
    """Describe the focused backend test command for one service."""
    if meta.tests_exist:
        tests_cmd_path = meta.tests_path.removeprefix("src/api/")
        return (
            f"`cd src/api && pytest {tests_cmd_path} -q` for the narrowest focused "
            "regression pass while iterating on this module."
        )

    return (
        f"`cd src/api && pytest -q` until `{meta.tests_path}` exists; create that "
        "directory first when this service gains behavior that needs focused "
        "regression coverage."
    )


def build_backend_spec(name: str, meta: BackendModuleMeta) -> DocSpec:
    """Build one backend service AGENTS.md spec."""
    title = f"Backend Service: {name}"
    key_files = (
        join_paths(
            *(f"src/api/flaskr/service/{name}/{path}" for path in meta.key_files)
        )
        if meta.key_files
        else "No checked-in source files are present yet."
    )
    migration_command = (
        '`cd src/api && FLASK_APP=app.py flask db migrate -m "message"` and review '
        "the generated revision if schema or indexed business-key changes are made."
        if meta.owns_models
        else "`cd src/api && pytest -q` is usually enough unless work here also "
        "changes shared models in another service."
    )
    related = list(meta.skill_refs)
    related.append("`src/api/SKILL.md`")
    related.append("`SKILL.md`")
    related.append(
        "Create a new backend skill under `src/api/skills/<topic>/SKILL.md` when "
        "this module grows a repeatable multi-step debugging workflow."
    )
    return DocSpec(
        title=title,
        intro=(
            f"This file adds local guidance for `src/api/flaskr/service/{name}`. "
            "Read the repository root and `src/api/AGENTS.md` first, then use "
            "this file for module-specific ownership and risk points."
        ),
        scope=(
            f"This service owns {meta.summary}.",
            f"Primary checked-in entry files today: {key_files}",
            "Keep behavior in this module unless the concern is clearly "
            "cross-service and shared by multiple backend domains.",
            f"Preferred pytest location: {maybe_tests_note(meta)}",
        ),
        do=(
            "Start from the local entry files and preserve how this service already "
            "structures helpers, models, routes, and DTO-like helpers.",
            sentence_case(meta.invariants[0]),
            sentence_case(meta.invariants[1]),
            sentence_case(meta.invariants[2]),
        ),
        avoid=(
            sentence_case(meta.avoid_points[0]),
            sentence_case(meta.avoid_points[1]),
            sentence_case(meta.avoid_points[2]),
            "Avoid scattering service-specific rules upward into root docs when "
            "the behavior only matters inside this module.",
        ),
        commands=(
            f'`rg -n "{name}" src/api/flaskr/service src/api/tests` to locate all '
            "backend call sites and tests before editing.",
            backend_test_command(meta),
            migration_command,
            "`cd src/api && pytest -q` when a change touches shared DTOs, auth, "
            "streaming contracts, or other services in addition to this module.",
        ),
        tests=(
            f"Add or update focused tests around `{meta.tests_path}` for the happy "
            "path and the highest-risk validation, permission, or failure case.",
            "Expand coverage when payload shapes, error codes, or shared helper "
            "contracts used outside this module change.",
            "Review persistence-related changes manually for indexing, business-key "
            "semantics, and migration output whenever models move.",
            "Document any skipped provider, network, or credential-dependent checks "
            "in the final task summary.",
        ),
        related_skills=tuple(related),
    )


def build_frontend_spec(name: str, meta: FrontendDomainMeta) -> DocSpec:
    """Build one frontend domain AGENTS.md spec."""
    title = f"Cook Web Domain: {name}"
    key_files = join_paths(*(f"src/web/src/{name}/{path}" for path in meta.key_files))
    focus_cmd_path = meta.test_focus.removeprefix("src/web/")
    related = list(meta.skill_refs)
    related.append("`src/web/SKILL.md`")
    related.append("`SKILL.md`")
    related.append(
        "Create a focused skill under `src/web/skills/<topic>/SKILL.md` when "
        "the same debugging or migration workflow repeats."
    )
    return DocSpec(
        title=title,
        intro=(
            f"This file adds local guidance for `src/web/src/{name}`. Read the "
            "repository root and `src/web/AGENTS.md` first, then use this file "
            "for domain-specific frontend ownership."
        ),
        scope=(
            f"This domain owns {meta.summary}.",
            f"Representative files in this subtree: {key_files}",
            "Keep durable frontend rules here only when they are more specific "
            "than the Cook Web-wide guidance in the parent directory.",
            f"Use focused frontend verification around `{meta.test_focus}` before "
            "widening to global type and lint checks.",
        ),
        do=(
            f"Start from the local entry files and preserve how `{name}` currently "
            "separates route code, shared logic, state, and utilities.",
            sentence_case(meta.invariants[0]),
            sentence_case(meta.invariants[1]),
            sentence_case(meta.invariants[2]),
        ),
        avoid=(
            sentence_case(meta.avoid_points[0]),
            sentence_case(meta.avoid_points[1]),
            sentence_case(meta.avoid_points[2]),
            "Avoid pushing domain-local rules up to shared docs unless another "
            "frontend subtree truly depends on the same constraint.",
        ),
        commands=(
            f'`rg -n "{name}" src/web/src` to locate call sites before editing '
            "this subtree.",
            "`cd src/web && npm run type-check` after TypeScript, store, hook, "
            "request, or route-contract changes.",
            "`cd src/web && npm run lint` before closing the task when shared "
            "frontend code or route files changed.",
            f"`cd src/web && npm run test -- {focus_cmd_path}` for focused Jest "
            "coverage when this subtree already has or gains tests.",
        ),
        tests=(
            f"Add or update focused tests closest to `{meta.test_focus}` for the "
            "happy path and the most important regression or business-code error path.",
            "Rerun type-checking and linting when exported props, store fields, "
            "hook contracts, or route behavior move.",
            "When a domain depends on shared request or normalization helpers, "
            "update those tests or add new ones in the same task.",
            "Document skipped UI, browser, or provider-dependent verification in "
            "the task summary when local automation cannot cover it.",
        ),
        related_skills=tuple(related),
    )


def render_rule(title: str, intro: str, bullets: tuple[str, ...]) -> str:
    """Render a Claude-only rule file."""
    lines = [DOC_COMMENT, "", f"# {title}", ""]
    lines.extend(wrap_paragraph(intro))
    lines.append("")
    for bullet in bullets:
        lines.extend(wrap_bullet(bullet))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_cursor_rule(
    title: str,
    description: str,
    bullets: tuple[str, ...],
    *,
    always_apply: bool,
    globs: tuple[str, ...] = (),
) -> str:
    """Render one Cursor MDC rule file."""
    lines = [
        "---",
        f"description: {description}",
        "globs:",
    ]
    lines.extend(f"  - {glob}" for glob in globs)
    lines.extend(
        [
            f"alwaysApply: {'true' if always_apply else 'false'}",
            "---",
            "",
            DOC_COMMENT,
            "",
            f"# {title}",
            "",
        ]
    )
    for bullet in bullets:
        lines.extend(wrap_bullet(bullet))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_copilot_repo_instructions(title: str, bullets: tuple[str, ...]) -> str:
    """Render repository-wide Copilot instructions."""
    lines = [DOC_COMMENT, "", f"# {title}", ""]
    for bullet in bullets:
        lines.extend(wrap_bullet(bullet))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_copilot_path_instructions(
    title: str,
    apply_to: str,
    bullets: tuple[str, ...],
) -> str:
    """Render one path-specific Copilot instructions file."""
    lines = [
        "---",
        f'applyTo: "{apply_to}"',
        "---",
        "",
        DOC_COMMENT,
        "",
        f"# {title}",
        "",
    ]
    for bullet in bullets:
        lines.extend(wrap_bullet(bullet))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_documents() -> dict[Path, str]:
    """Build generated module AGENTS.md files and thin tool-private routers."""
    cursor_repo = AGENTS_ONLY_POINTER + CURSOR_PRIVATE_POINTER
    cursor_path = AGENTS_ONLY_POINTER + CURSOR_PRIVATE_POINTER + PATH_AGENTS_POINTER
    copilot_repo = AGENTS_ONLY_POINTER + COPILOT_PRIVATE_POINTER
    copilot_path = AGENTS_ONLY_POINTER + COPILOT_PRIVATE_POINTER + PATH_AGENTS_POINTER
    docs: dict[Path, str] = {
        ROOT / ".cursor" / "rules" / "repository-ai-collab.mdc": render_cursor_rule(
            "Cursor Rule: Repository AI Collaboration",
            "Repository-wide pointer to native AGENTS.md",
            cursor_repo,
            always_apply=True,
        ),
        ROOT / "docs" / ".cursor" / "rules" / "design-workflow.mdc": render_cursor_rule(
            "Cursor Rule: Docs Knowledge Workflow",
            "Documentation workflow pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
        ),
        ROOT / ".cursor" / "rules" / "github-workflows.mdc": render_cursor_rule(
            "Cursor Rule: GitHub Workflows",
            "GitHub Actions pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
            globs=(".github/workflows/**",),
        ),
        ROOT / ".cursor" / "rules" / "docker-ops.mdc": render_cursor_rule(
            "Cursor Rule: Docker",
            "Docker pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
            globs=("docker/**",),
        ),
        ROOT / ".cursor" / "rules" / "scripts-maintenance.mdc": render_cursor_rule(
            "Cursor Rule: Scripts",
            "Scripts pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
            globs=("scripts/**",),
        ),
        ROOT
        / "src"
        / "api"
        / ".cursor"
        / "rules"
        / "backend-api.mdc": render_cursor_rule(
            "Cursor Rule: Backend API",
            "Backend pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
        ),
        ROOT / "src" / "web" / ".cursor" / "rules" / "web.mdc": render_cursor_rule(
            "Cursor Rule: Cook Web",
            "Frontend pointer to native AGENTS.md",
            cursor_path,
            always_apply=False,
        ),
        ROOT / ".github" / "copilot-instructions.md": render_copilot_repo_instructions(
            "Copilot Repository Instructions",
            copilot_repo,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "ai-instructions.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: AI Collaboration Files",
            (
                "AGENTS.md,SKILL.md,.claude/**/*.md,.cursor/rules/**/*.mdc,"
                ".github/AGENTS.md,.github/copilot-instructions.md,"
                ".github/instructions/**/*.instructions.md,docker/AGENTS.md,"
                "scripts/AGENTS.md,src/api/**/AGENTS.md,src/api/SKILL.md,"
                "src/api/skills/**/*.md,src/web/**/AGENTS.md,src/web/SKILL.md"
            ),
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "backend.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: Backend",
            "src/api/**/*.py,src/api/**/*.md,src/i18n/**/*.json",
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "frontend.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: Frontend",
            (
                "src/web/**/*.ts,src/web/**/*.tsx,src/web/**/*.js,"
                "src/web/**/*.jsx,src/web/**/*.css,src/web/**/*.scss,"
                "src/web/**/*.md,src/web/**/*.mdx"
            ),
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "docs.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: Docs Workflow",
            "docs/**/*.md,PLANS.md,ARCHITECTURE.md",
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "docker.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: Docker",
            "docker/**/*.yml,docker/**/*.yaml,docker/**/*.sh,docker/**/*.conf,docker/.env.example.full",
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "scripts.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: Scripts",
            "scripts/**/*.py,scripts/**/*.js,scripts/**/*.md",
            copilot_path,
        ),
        ROOT
        / ".github"
        / "instructions"
        / "workflows.instructions.md": render_copilot_path_instructions(
            "Copilot Instructions: GitHub Workflows",
            ".github/workflows/**/*.yml,.github/workflows/**/*.yaml",
            copilot_path,
        ),
    }

    for name, meta in BACKEND_META.items():
        service_dir = ROOT / "src" / "api" / "flaskr" / "service" / name
        docs[service_dir / "AGENTS.md"] = render_agents(build_backend_spec(name, meta))

    for name, meta in FRONTEND_META.items():
        domain_dir = ROOT / "src" / "web" / "src" / name
        docs[domain_dir / "AGENTS.md"] = render_agents(build_frontend_spec(name, meta))

    return docs


def write_documents() -> int:
    """Write all generated docs to disk."""
    docs = build_documents()
    for path, content in sorted(docs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(docs)} AI collaboration documents.")
    return 0


def main() -> int:
    """Regenerate module AGENTS.md files and thin tool-private routers."""
    return write_documents()


if __name__ == "__main__":
    raise SystemExit(main())
