name: deploy test
on:
  pull_request:
jobs:
  checkout-pr:
    if: github.repository == 'ai-shifu/ai-shifu'
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ github.token }}
    # steps:
    #   - name: Checkout PR
    #     run: |
    #       git reset --hard FETCH_HEAD
    #       gh pr checkout ${{ github.event.pull_request.number }}
    #   - name: Build and Sync API
    #     run: |
    #       bash scripts/deploy-develop/deploy-shifu-api-test.sh
    #   - name: Build and Sync Web
    #     run: |
    #       bash scripts/deploy-develop/deploy-shifu-web-test.sh
    #   - name: Build and Sync Admin Web
    #     run: |
    #       bash scripts/deploy-develop/deploy-shifu-admin-web-test.sh
