name: deploy sifu api test

on:
  push:
    branches: ["develop"] # Trigger only on push to the develop branch

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH to remote server and execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            cd /item/cd ai-shifu
            git checkout develop
            git pull
            bash /item/ai-shifu/scripts/deploy-develop/deploy-shifu-api-test.sh
            bash /item/ai-shifu/scripts/deploy-develop/deploy-shifu-web-test.sh
